### ISSUE TITLE
elastic-package fails if there is more than one scenario in with-custom-agent

### ISSUE THREAD

**Issue by mrodm** [elastic/elastic-package#1023]
Seen in this PR https://github.com/elastic/elastic-package/pull/1009
Relates https://github.com/elastic/elastic-package/issues/997

After adding a new package into the test suite of `with-custom-agent`, it looks like that after running the first run of the system testing (with auditbeat package), there are some leftovers or conditions that make the second run with the oracle pckage to fail.

**Comment by agithomas** [comment]
Details of scenario can be found [here](https://docs.google.com/document/d/1QOwWmkeezid_v2A8fZMMx-w2QJZmKeGgkglltXOzvBQ/edit)

**Comment by agithomas** [comment]
PR Link : https://github.com/elastic/elastic-package/pull/1024
