### ISSUE TITLE
Support input packages in elastic-package dump

### ISSUE THREAD

**Issue by jsoriano** [elastic/elastic-package#1050]
`elastic-package dump` is not working for input packages. For example:
```
$ elastic-package dump installed-objects -P jolokia
No objects were dumped for package jolokia, is it installed?
```
But it is installed:
![Captura desde 2022-11-24 12-00-29](https://user-images.githubusercontent.com/15763/203768171-eb9ae6e3-e6af-4627-9d40-004f1beaf913.png)

**Comment by jsoriano** [comment]
It seems that the problem is that nothing is installed for input packages, so it may be fine.

**Comment by jlind23** [comment]
@jsoriano @hop-dev Is this issue still relevant with the latest changes we did on input packages?

**Comment by hop-dev** [comment]
I'm not so familiar with elastic-package dump. Thats right that nothing is installed for input packages on first install.

But for input packages, would we want to dump the index templates and ingest pipelines that are created per package policy (and does it work as expected now?)

**Comment by jsoriano** [comment]
> Thats right that nothing is installed for input packages on first install.

Then it is fine if nothing is dumped after first install. Perhaps we should check if the requested package is actually installed, and change the error message.

> But for input packages, would we want to dump the index templates and ingest pipelines that are created per package policy (and does it work as expected now?)

Yeah, it'd be great if they are dumped when using `elastic-package dump` with an input package. Are they now?
