### ISSUE TITLE
`export dashboard` should strip tags created by Fleet

### ISSUE THREAD

**Issue by joshdover** [elastic/elastic-package#1060]
Repro steps:
1. `elastic-package stack up`
2. Install the package you're developing - Fleet adds a `Managed` and `<package name>` tag to the dashboards by default
3. Make changes to dashboard
4. `elastic-package export dashboard -d <id>` will export the tag automatically created by Fleet
5. Now there's a tag in the package and one created by Fleet, which will result in duplicate tags of the same name when a package is installed later

In integrations repo, file search against "kibana/tags" and you'll see packages with the Fleet-created tags exported:
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/1965714/227316016-43a968e6-616d-4ad9-bff9-1880faed1ec7.png">

**Comment by P1llus** [comment]
Its a shame that we cannot use the same tags over different packages because of the package name being added to the ID of the tag.

For security integrations as an example, having certain integrations grouped by tags would be good for visibility when searching for specific types of dashboards etc.

**Comment by jsoriano** [comment]
There was another report of this in https://github.com/elastic/elastic-package/issues/1098.
