### ISSUE TITLE
Add support to upload packages directly to Kibana/Fleet

### ISSUE THREAD

**Issue by ruflin** [elastic/elastic-package#1084]
In https://github.com/elastic/kibana/issues/70582 the Fleet team is working on adding an API to support uploading packages directly to Kibana. `elastic-package` should have a command available that allows to use this API. The initial idea I had was:

```
elastic-package upload --kibana=http://localhost:5601
```

In case this is run inside a package, the package is built and then uploaded to Kibana. Alternatively if a package zip file already exists, the following could be used:

```
elastic-package upload --path=/foo/bar/package.zip --kibana=http://localhost:5601
```

In this scenario, elastic-package assumes the package inside the zip file is already validated.

**Comment by jsoriano** [comment]
We have the `elastic-package install` command to install packages, should we update this subcommand instead of adding a new one? Having two for the same thing may be confusing.

**Comment by ruflin** [comment]
No strong opinion on my end around naming, the above is not necessarily a proposal on how we should name things and structure the params, much more to explain it.

For everyone curious on what the install command does: 

> The command uses Kibana API to install the package in Kibana. The package must be exposed via the Package Registry.

**Comment by amitkanfer** [comment]
@juliaElastic is this related to https://github.com/elastic/kibana/issues/148599 ?

**Comment by juliaElastic** [comment]
@amitkanfer Yes, this is a planned improvement in `elastic-package` to support the `upload` command. It is for convenience to call the Fleet API.

**Comment by jsoriano** [comment]
Once we have this, https://github.com/elastic/elastic-package/issues/1157 can be a low hanging fruit. https://github.com/elastic/elastic-package/issues/1157 will help with development experience and reliability.

**Comment by mrodm** [comment]
This issue could be done in different steps:
- Add a new `--zip` parameter into the install command that just installs the given zip file
    - https://github.com/elastic/elastic-package/pull/1160
- Update install command to build and use that zip to install (just if Elastic stack >= 8.7.0)

**Comment by jlind23** [comment]
@mrodm If you have could you please think about recording a demo for this? 😄
