### ISSUE TITLE
elastic-package starts but does nothing Windows 11

### ISSUE THREAD

**Issue by joeperuzzi** [elastic/elastic-package#1100]
Installing the elastic-package through go and/or running it stand-alone pre-compiled takes CPU cycles but never moves.  No matter what switches are used, the executable doesn't seem to do anything but take CPU cycles.  I've let this run for 20 minutes and nothing happens other than CPU usage, i've disabled all AV (running Elastic Endpoint) as it was causing the Elastic Security process to consume all the CPU and crash explorer.

Currently Running on Windows 11 Pro 10.0.22621 on an Intel i7.  

<img width="926" alt="image" src="https://user-images.githubusercontent.com/122561341/213224426-2181020e-3f73-48c1-8fda-d70736388dce.png">
<img width="467" alt="image" src="https://user-images.githubusercontent.com/122561341/213252499-0bdc462c-5b82-4fc8-8976-b638d99fd253.png">

**Comment by joeperuzzi** [comment]
I executed "go install github.com/elastic/elastic-package@latest" yesterday, the executable will not run to give me a version and the exe properties that is generated from that command does not have a version in its properties.

**Comment by jsoriano** [comment]
@joeperuzzi can you try with one of the released versions? https://github.com/elastic/elastic-package/releases

**Comment by joeperuzzi** [comment]
I tried both 0.70 and 0.71 both have the same outcome as above.

**Comment by joeperuzzi** [comment]
Just as an update, downloaded and tested  v0.74.0 and the issue still exists.

**Comment by joeperuzzi** [comment]
Just as an update, downloaded and tested v0.75.0 and the issue persists 

<img width="672" alt="image" src="https://user-images.githubusercontent.com/122561341/222216622-5a8657f7-79e1-4589-9226-83d3e16f9897.png">

**Comment by jsoriano** [comment]
@joeperuzzi thanks. We haven't been able to reproduce it, so by now you are our only hope to catch this issue :slightly_smiling_face:

Could you try to investigate the process with other tools, like [Process Monitor](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon), to see if you can see something else?

Would you have the chance to try to run another Go program, even if it is just a hello world, to see if it is an issue with Go runtime?

**Comment by joeperuzzi** [comment]
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/122561341/222589694-8bbdc4e6-30f8-4345-a6bb-71224ba2f84c.png">
Seems to be trying to write the c:\.git file and is failing...

**Comment by joeperuzzi** [comment]
I manually created an empty.git file 
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/122561341/222590263-5e9bea18-d9f9-4c77-b73e-2181e2406b50.png">

**Comment by joeperuzzi** [comment]
@jsoriano I removed the .git file and created a c:\.git folder and the command line now works:

C:\Users\peruz\Downloads\elastic-package_0.75.0_windows_amd64.tar>elastic-package.exe version
elastic-package v0.75.0 version-hash 47a2456 (build time: 2023-02-23T07:57:31-07:00)

C:\Users\peruz\Downloads\elastic-package_0.75.0_windows_amd64.tar>

**Comment by jsoriano** [comment]
Hey @joeperuzzi,

This is useful, this pointed me to the [`FindRepositoryRootDirectory()` function](https://github.com/elastic/elastic-package/blob/44b5019705734a6985759374d726e29488c2110a/internal/files/repository.go#LL14C53-L14C53). Looking to the implementation it may be looping forever in some cases in Windows. It has a finalization condition that checks if the directory name is `/`. This will never be satisfied on this platform.

I wonder though why it reports to be creating a file, it should be only checking its attributes, maybe this is how the implementation works in Windows.

And I wonder too why `elastic-package -h` ends up calling this function, it shouldn't need it.

I will take a look by now to this finalization condition.

Thanks!

**Comment by jsoriano** [comment]
@joeperuzzi could you give a try to this patch in your scenario? https://github.com/elastic/elastic-package/pull/1171

**Comment by jsoriano** [comment]
I have been able to reproduce the issue by running `elastic-package` out of a git repository. I could also confirm that https://github.com/elastic/elastic-package/pull/1171 fixes the issue for me. I am opening this PR for review and merge.

**Comment by joeperuzzi** [comment]
@jsoriano  sorry i've been traveling and haven't been able to do this check.  I'm not building or executing from source.  I'll retest on the next package release which would be a better test case for resolution.
