### ISSUE TITLE
[K8s testing] Support use of Kustomize

### ISSUE THREAD

**Issue by constanca-m** [elastic/elastic-package#1102]
## What does this issue try to achieve?
Updating kube state metrics version on testing at most one time.

## What is the problem?
Right now, the current kube state metrics version being used for Kubernetes integration testing is `2.3.0`. 
However, this version is no longer aligned with the Kubernetes version being supported, which range between
`1.23.x`-`1.26.x`. This implies that, at least, there should be support for `2.4.2` version - and this version should keep being incremented at the same time Kubernetes versions are released and supported by the integration. 

Example of a problem the current being used version is causing (also documented [here](https://github.com/elastic/integrations/blob/main/packages/kubernetes/docs/kube-state-metrics.md#state_cronjob)):
```
DEBUG found 0 hits in metrics-kubernetes.state_cronjob-ep data stream: index_not_found_exception: no such index [metrics-kubernetes.state_cronjob-ep] Status=404
```
This causes our tests to fail and makes it impossible to merge PRs on our Kubernetes integration.

The problem is that changing this version, doesn't apply changing only one tag. We need to:
- Update tag on five different files (the ones related to kube state metrics), and, on top of that:
- We need to update other things, such [as permissions](https://github.com/elastic/integrations/pull/5012#pullrequestreview-1254056620).

This can be seen on [this PR](https://github.com/elastic/integrations/pull/5061).

This is, of course, not ideal and this process should not require such high maintenance. Since, Kustomize is already being used ([see from this PR](https://github.com/elastic/elastic-agent/pull/2104)), the same approach should be followed.

## Steps this would require

We would need to:

1. [In elastic package repository](https://github.com/elastic/elastic-package) Change flag `-f` on kubectl to `-k` in [here](https://github.com/elastic/elastic-package/blob/main/internal/kubectl/kubectl.go) to allow (and enforce) the use of Kustomize;
2. [In integrations repository](https://github.com/elastic/integrations) Update [files](https://github.com/elastic/integrations/tree/main/packages/kubernetes/_dev/deploy/k8s) in a way that a new `kustomization.yaml` file is deployed, that will simultaneously apply kube-state-metrics from the original repository. Same approach as shown in this merged [PR](https://github.com/elastic/elastic-agent/pull/2104);
3. Document this (maybe in this [file](https://github.com/elastic/elastic-package/blob/main/docs/howto/system_testing.md#kubernetes-service-deployer)).

Making this change will let us update kube-state-version by changing just one word: the reference to the branch we are targeting. And if we always want to use the latest version we won't even have to do that.

## Which packages does this affect?

As of the moment this issue is created, the only package that will be affected by this change will be Kubernetes.
The reason for this, is that only integrations with this kind of folder `_dev/deploy/k8s` are considered on Kubernetes testing. There are three integrations with one: Kubernetes, Cloud Defend and Cloud Security Posture. However, as documented [here](https://github.com/elastic/elastic-package/blob/main/docs/howto/system_testing.md#kubernetes-service-deployer), since the last two have the `.empty` file, only the Kubernetes integration makes use of this test.

**Comment by gsantoro** [comment]
Maybe since we are there we should look into how they are using:
- https://github.com/elastic/elastic-package/blob/main/internal/kubectl/kube-state-metrics-single.yaml
- https://github.com/elastic/elastic-package/blob/main/internal/kubectl/kube-state-metrics-multiple.yaml

**Comment by constanca-m** [comment]
> Maybe since we are there we should look into how they are using:
> 
>     * https://github.com/elastic/elastic-package/blob/main/internal/kubectl/kube-state-metrics-single.yaml
> 
>     * https://github.com/elastic/elastic-package/blob/main/internal/kubectl/kube-state-metrics-multiple.yaml

I don't really understand where those files are being used, but since they relate to the same thing, I agree we should look into that as well @gsantoro

**Comment by gsantoro** [comment]
I couldn't find them referenced anywhere but we should ask around.

**Comment by tetianakravchenko** [comment]
I don't think we should enforce use of Kustomize,  if usage of manifests stored in `_dev/deploy/k8s` covers all needs and there is no reason to use kustomization.yml - this should be supported

**Comment by gsantoro** [comment]
1. I agree that we should support `kustomize` as optional. I was thinking that if we were to add some extra logic that only support kustomize if there is a `kustomization.yml` in that directory that would be better.
2. the alternative there could be something along the line 

```bash
if test -f "./kustomization.yml"; then
  kustomize build | kubectl apply -f - -o yaml
else
  cat manifest.yaml | kubectl apply -f - -o yaml
fi
```

**Comment by constanca-m** [comment]
I was thinking in forcing a kustomization file only for the custom directory. Since we use elastic agent files similarly as a user would use through Kibana, I don't think it is a good idea to change that without a discussion @gsantoro @tetianakravchenko . And since we only use the custom directory for the `state_*` datastreams, we know that we need to deploy kube state metrics and there is no need to maintain those files.

**Comment by gsantoro** [comment]
1. yes, we should discuss it with the elastic-package team either way
2. when you say `we only use the custom directoy for the state_* datastream` do you mean this directory? `packages/kubernetes/data_stream/state_cronjob/_dev/test/system`. since we also have system tests at `packages/kubernetes/data_stream/proxy/_dev/test/system`.
3. Also FYI, at `packages/kubernetes/_dev/deploy/k8s` there is more than just the kube-state-metrics service. 
4. Also FYI, I could use the `kustomization.yaml` in the system tests to fix this issue https://github.com/elastic/integrations/issues/4874 where I need to fix the order of two manifests for that to work.

**Comment by constanca-m** [comment]
> 1. yes, we should discuss it with the elastic-package team either way
> 
>     2. when you say `we only use the custom directoy for the state_* datastream` do you mean this directory? `packages/kubernetes/data_stream/state_cronjob/_dev/test/system`. since we also have system tests at `packages/kubernetes/data_stream/proxy/_dev/test/system`.
> 
>     3. Also FYI, at `packages/kubernetes/_dev/deploy/k8s` there is more than just the kube-state-metrics service.
> 
>     4. Also FYI, I could use the `kustomization.yaml` in the system tests to fix this issue [Craft a system test for nginx_ingress_controller integration that works with k8s integrations#4874](https://github.com/elastic/integrations/issues/4874) where I need to fix the order of two manifests for that to work.

2. No, sorry, I should have made it explicit. I mean this one `packages/kubernetes/_dev/deploy/k8s`
3. Yes, I noticed, I was thinking in putting them as resources on the kustomization.yaml
4. Ok, as soon as I can make it work locally, I will look into that.

@gsantoro

**Comment by gsantoro** [comment]
I'm not 100% sure which resources for elastic-agent you are talking about. either way, let's have a look once you make the change and have all the system tests working.

**Comment by tetianakravchenko** [comment]
@constanca-m I also don't fully follow you here, regarding this part:
```
the manifests file deploying anything related to elastic agent will be left as they are now, and they will keep being deployed with the -f flag. The only ones that will use kustomize, will be the custom resources for our package (packages/kubernetes/_dev/deploy/k8s) that are used by all state_* datastreams.
```

but as mentioned above - let's have a look once you make the change

**Comment by gizas** [comment]
Trying to summarize all above discussion:
1. @constanca-m to update `packages/kubernetes/_dev/deploy/k8s` with Kustomize
2. For `nginx-ingress-controller` lets not touch it as part of this story as we have the relevant one. 
3. For `elastic-package` enhancement I agree lets not enforce it as only option. Lets just suggest it to the team if they want to follow this path to have kustomize as an alternative

**Comment by gsantoro** [comment]
@gizas I have added details about nginx-ingress-controller to the linked issue `Use Kustomize to deploy resources`

**Comment by constanca-m** [comment]
>     3. For `elastic-package` enhancement I agree lets not enforce it as only option. Lets just suggest it to the team if they want to follow this path to have kustomize as an alternative

@gizas I don't think I expressed myself well on this, but once I open the PR it will become more clear
