### ISSUE TITLE
Upload locally-built package to Ingest Manager

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-package#114]
Not sure if this needs to be a separate subcommand or built into existing subcommands (like `test system`) or both, but we should allow users to build and upload a local package into the local Ingest Manager, once https://github.com/elastic/kibana/pull/77986 has been implemented. This will remove the need for rebuilding the local registry any time a package developer makes changes to their local package files.

**Comment by ycombinator** [comment]
https://github.com/elastic/kibana/pull/77986 has just been merged so we can now start working on this feature.

**Comment by ycombinator** [comment]
Oh, didn't realize that. Thanks @ph.

**Comment by mtojek** [comment]
@ycombinator I think there is a plan for such command: https://github.com/elastic/elastic-package/issues/8

**Comment by ycombinator** [comment]
Thanks, closing this as a duplicate of #8.
