### ISSUE TITLE
Use package upload instead of registry for development

### ISSUE THREAD

**Issue by ruflin** [elastic/elastic-package#1157]
With the current development setup, each time a package is modified it is pushed to the registry and then a Kibana API call is made to trigger the installation. In Kibana, the upload API just landed (https://github.com/elastic/kibana/issues/148599) and soon I expect the upload command will exist in elastic-package: https://github.com/elastic/elastic-package/issues/1084

Having these 2 components, I suggest to simplify the development flow by pushing packages directly to Kibana during development instead of going through the registry. This should be faster and also provide direct feedback in case some assets are not configured properly.

**Comment by jsoriano** [comment]
+1 to this, but we have to keep both implementations for current versions that don't have the upload API.

**Comment by jsoriano** [comment]
https://github.com/elastic/elastic-package/pull/1281 fixed this.
