### ISSUE TITLE
Add end-to-end benchmark command

### ISSUE THREAD

**Issue by marc-gr** [elastic/elastic-package#1164]
Expand the `benchmark` command to add end-to-end capabilities in addition to pipeline ones.

Having a working cluster and a set of agent hosts enrolled, we want to run benchmark scenarios for a given package version and data stream.

Requirements:

- A spec to define benchmark scenarios https://github.com/elastic/package-spec/issues/483

Scope:

- Set up the custom policy
- Start the benchmark services containing the required tooling to deliver the logs
- Run these services
- Collect results
- Stop benchmark services

Not in scope for the command:

- Manage the required infrastructure - it expects a working fleet setup
- ~Generate corpora data on-the-fly - it needs to be pre-generated~

**Comment by aspacca** [comment]
> * Generate corpora data on-the-fly - it needs to be pre-generated

for generating data on-the-fly we are working on https://github.com/elastic/elastic-package/issues/1110

currently in a separated command, I'll move as subcommand of `benchmark`
