### ISSUE TITLE
De-dupe data stream fields

### ISSUE THREAD

**Issue by jen-huang** [elastic/elastic-package#1195]
`elastic-package check` should error when a package data stream has the same field declared more than once. Example below:

> I see `event.module` declared twice for the system security data stream:
> 
> 1. First in `base-fields.yml` as `constant_keyword`: [LOC](https://github.com/elastic/package-storage/blob/5df4ae7dbfa2455da2a9782f9126bf29f70c5709/packages/system/1.20.4/data_stream/security/fields/base-fields.yml#L14)
> 2. Second in `ecs.yml` as `keyword`, parsed after package is built: [LOC](https://github.com/elastic/package-storage/blob/5df4ae7dbfa2455da2a9782f9126bf29f70c5709/packages/system/1.20.4/data_stream/security/fields/ecs.yml#L46)
> 
> This is causing an issue where Fleet is using the second declaration, `keyword` type, for the index settings. See https://github.com/elastic/kibana/issues/127866 for more details.
> 
> A fix is going into Kibana to de-dupe fields, but I believe we should de-dupe the field definition lists as well. It seems that most other packages only declare `event.module` in `base-fields.yml`.

**Comment by jsoriano** [comment]
Implemented in package spec v2. Packages need to update their `format_version` to leverage this.
