### ISSUE TITLE
Review documentation templates and helpers for input packages

### ISSUE THREAD

**Issue by jsoriano** [elastic/elastic-package#1223]
On https://github.com/elastic/integrations/pull/5890 some issues are identified when trying to generate documentation for input packages, review these use cases and provide better support for these packages.

**Comment by jlind23** [comment]
Closing this as outdated/not prioritised, we will reopen if required. cc @kpollich

**Comment by jsoriano** [comment]
We should probably address this at some point. Last time we checked, the helpers that we have for integration package docs don't work for input packages. It is probably a small task.

**Comment by jlind23** [comment]
I'll leave this to you and @kpollich then.

**Comment by jsoriano** [comment]
Took a quick look to this and it seems that we were missing support only in the `event` helper, adding support for this in https://github.com/elastic/elastic-package/pull/1998.
