### ISSUE TITLE
Support testing packages with multiple data fidelity modes

### ISSUE THREAD

**Issue by jsoriano** [elastic/elastic-package#1247]
When a package defined multiple data fidelity modes, its tests should try to use all of them. Data fidelity modes are defined in the spec on https://github.com/elastic/package-spec/issues/517.

Changes needed for this:
* Pipeline tests use the simulate API to test pipelines. It should be able to install the specific templates for each fidelity mode, according to the spec definition. 
* System tests should be able to configure policies with the different fidelity modes.
* Fields validations should be able to interpret the fields available for each fidelity mode.

Related to:
* https://github.com/elastic/package-spec/issues/517
* https://github.com/elastic/package-spec/issues/518

**Comment by jlind23** [comment]
We have been able to achieve greater storage reduction by tackling other issues such as reducing the log level or changing the metric collection frequency, hence closing this for now.
