### ISSUE TITLE
Check fields duplication

### ISSUE THREAD

**Issue by tetianakravchenko** [elastic/elastic-package#1287]
It is possible to define the same field multiple times in `<package-name>/fields/` folder. If the definition of this fields are different - it might cause unexpected changed wen runnin `elastic-package build`, example: https://github.com/elastic/integrations/pull/6118#discussion_r1196327806

I think it would be helpful to add check on duplicated fields when executing `elastic-package check`

**Comment by jsoriano** [comment]
This check (along some others), is already available in package spec v2 (https://github.com/elastic/package-spec/issues/331). Try updating `format_spec` in the manifest to a recent version, like `format_version: 2.8.0`.

If you find issues upgrading to this major, take a look to these guidelines: https://github.com/elastic/elastic-package/blob/main/docs/howto/update_major_package_spec.md
