### ISSUE TITLE
f1106b9b causes build failures due to valid log lines

### ISSUE THREAD

**Issue by efd6** [elastic/elastic-package#1296]
Since f1106b9b valid builds can fail with 
```
Error: error running package system tests: could not complete test run: check log messages failed: malformed docker-compose log line
```
With judicious addition of information to the error message:
```diff
diff --git a/internal/stack/parselogs.go b/internal/stack/parselogs.go
index 6b8557e..a2d62b6 100644
--- a/internal/stack/parselogs.go
+++ b/internal/stack/parselogs.go
@@ -41,7 +41,7 @@ func ParseLogs(options ParseLogsOptions, process func(log LogLine) error) error
                messageSlice := strings.SplitN(line, "|", 2)

                if len(messageSlice) != 2 {
-                       return fmt.Errorf("malformed docker-compose log line")
+                       return fmt.Errorf("malformed docker-compose log line: %q", line)
                }

                messageLog := messageSlice[1]
```
we see
```
Error: error running package system tests: could not complete test run: check log messages failed: malformed docker-compose log line: "Attaching to elastic-package-stack_elastic-agent_1"
```
Replacing the error return with a `continue` allows completion of the assessment of log lines that appears to be the intention of #1256.

/cc @mrodm

**Comment by mrodm** [comment]
@efd6 What docker-compose version was used in those executions ? Maybe v1.x?

**Comment by efd6** [comment]
A bunch of people are seeing it. I am using v1, but I can't speak for others.

**Comment by ebeahan** [comment]
`docker-compose` v1.x is what installs alongside Docker Desktop on Mac: 

<img width="767" alt="Screenshot 2023-06-07 at 8 00 53 AM" src="https://github.com/elastic/elastic-package/assets/7226265/3b9e410f-82ea-45af-a7c6-97889b11c04b">
