### ISSUE TITLE
Automate update of package-spec version set in new packages manifest

### ISSUE THREAD

**Issue by mrodm** [elastic/elastic-package#1304]
When creating new packages by the `elastic-package create package` command, the package-spec version is set there (`format_version` key). This package-spec version is defined in a template: [format_version definition](https://github.com/elastic/elastic-package/blob/4fd1b5875a6260ebc50a37ede399cbba95245b2c/internal/packages/archetype/package_manifest.go#L7)

This version should be updated automatically when there is a new tag pushed in package-spec repository, creating a new PR like this one https://github.com/elastic/elastic-package/pull/1303

One approach for this could be create a Github action workflow or a Buildktie workflow that is triggered on a schedule (like cron) checking if there is a new tag, and if so create the required PR.

**Comment by mrodm** [comment]
It looks like that this issue can be already closed thanks to this PR: https://github.com/elastic/elastic-package/pull/1426

In that PR, package-spec dependency is used to set that `format_version` key via the `GetLatestStableSpecVersion` method. I think this issue could be closed, WDYT @jsoriano ?

**Comment by jsoriano** [comment]
Yes, I'd say so, closing.
