### ISSUE TITLE
Support for Docker Compose V2 + Compose V1 Nearing End of Life

### ISSUE THREAD

**Issue by nicpenning** [elastic/elastic-package#1306]
I have been testing the elastic-package tool inside of Windows Subsystem for Linux (WSL2) and have used the latest Docker installation that uses Compose V2 which is `docker compose`. This in turn then does not work with elastic-package as it expects `docker-compose`

```
napsta@TESTLL:~$ elastic-package stack up -d -v
2023/06/13 10:43:32 DEBUG Enable verbose logging
Boot up the Elastic stack
Using profile /home/napsta/.elastic-package/profiles/default.
Remember to load stack environment variables using 'eval "$(elastic-package stack shellinit)"'.
Elasticsearch host: https://127.0.0.1:9200
Kibana host: https://127.0.0.1:5601
Username: elastic
Password: changeme
Local package-registry will serve packages from these sources:
- Proxy to https://epr.elastic.co
2023/06/13 10:43:33 DEBUG running command: docker-compose version --short
2023/06/13 10:43:33 ERROR Unable to determine Docker Compose version: running Docker Compose version command failed: exec: "docker-compose": executable file not found in $PATH. Defaulting to 1.x
2023/06/13 10:43:33 DEBUG running command: docker-compose -f /home/napsta/.elastic-package/profiles/default/stack/snapshot.yml -p elastic-package-stack build
Error: booting up the stack failed: building docker images failed: running command failed: running Docker Compose build command failed: exec: "docker-compose": executable file not found in $PATH
```

Here are the documents to migrating to Compose V2. It seems like V1 (docker-compose) is End of Life June 2023 (this month) which means it will no longer receive updates.

https://docs.docker.com/compose/migrate/

Is this something in the works or being considered?

**Comment by adam-stokes** [comment]
I think I'm running into this issue now trying to get elastic-package running on ubuntu 22.04, even with docker-compose package installed.  

```
ubuntu@ogc-layout-8zv8obfc:~$ sudo docker version
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:07:41 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:07:41 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.25
  GitCommit:        d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

```
ubuntu@ogc-layout-8zv8obfc:~$ elastic-package version
elastic-package v0.95.0 version-hash 55d587a (build time: 2023-12-08T17:16:14Z)
```

/cc @ruflin I may be able to work around this for now, but this may become more of an issue sooner than later

**Comment by jsoriano** [comment]
@adam-stokes do you have the `docker-compose` command in your `PATH`? Having the `docker compose` subcommand is not enough.

**Comment by adam-stokes** [comment]
> @adam-stokes do you have the `docker-compose` command in your `PATH`? Having the `docker compose` subcommand is not enough.

I had both docker and the docker compose plugin installed from the official docker repo and also ad the docker-compose package installed, though i dont know which repo that was from

**Comment by jsoriano** [comment]
> > @adam-stokes do you have the `docker-compose` command in your `PATH`? Having the `docker compose` subcommand is not enough.
> 
> I had both docker and the docker compose plugin installed from the official docker repo and also ad the docker-compose package installed, though i dont know which repo that was from

Could you copy the error that you are having? Is it the same as the one reported in the issue?

Also, could you share the output of `docker-compose version`?

**Comment by adam-stokes** [comment]
I switched to ubuntu 2004 with `docker-compose version 1.25.0, build unknown` and things seemed to progress a little bit further.

**Comment by jsoriano** [comment]
I currently have Ubuntu 22.04 with `Docker Compose version v2.14.1`, and it works for me. I will try to update docker compose.

**Comment by jsoriano** [comment]
Works for me also with latest version of standalone docker compose, `Docker Compose version v2.23.3`.

It'd be good to have the specific error.
