### ISSUE TITLE
Add tooling to discover on what Elastic offerings a package will be available

### ISSUE THREAD

**Issue by jsoriano** [elastic/elastic-package#1343]
Once we have offerings with different feature sets, it would be nice to have some tooling to help package developers to discover on what offerings their packages are going to be available.

We need to define how this tooling may work, some ideas:
* Have a hard-coded list of offerings and capabilities so elastic-package can check there.
* Check if there is an API to check the list of offferings and their capabilities.
* Rely on the [configuration files](https://github.com/elastic/kibana/tree/bfab1b0659269cf67d6a864d6a80ee29632b4b4c/config).

Regarding the tool, it could be a subcommand of elastic-package, or be part of `elastic-package status`.

Package capabilties are defined in https://github.com/elastic/package-spec/issues/560.

**Comment by jlind23** [comment]
As per our conversation, assigning this to you @jsoriano
