### ISSUE TITLE
[system test] System test fails with TSDB enablement on 8.8.0 stack 

### ISSUE THREAD

**Issue by agithomas** [elastic/elastic-package#1365]
**Issue Summary**

- If TSDB enablement is attempted on an Integration package, having multiple variants for system test, CI/CD pipeline fails. 
- It is not possible to add multiple variants for system testing, if TSDB enablement is already made on that integration package. 

Please note the conditions below to observe the issue
**ES Version** : 8.8.0

**Tested with** : Postgresql, MySQL, Nginx integrations (with multiple variants entries added)

**Steps to recreate** : 

- Use nginx (because it is already tsdb enabled and code/config changes may be needed for testing with PostgreSQL / MySQL
- Add a new entry to the variants.yml file as below
```
variants:
  v1:
    SERVICE_VERSION: 1.19.5
  v2:
    SERVICE_VERSION: 1.24.0
default: v1
```
- Run command:  `elastic-package test system -d stubstatus -v` with nginx integration

**What you observe** : 
```
2023/07/24 04:25:03 DEBUG Agent data: {"id":"62a3c8fc-7c19-4f0d-8fa9-e87913e7ed5c","policy_id":"0428b4d0-29da-11ee-ae80-6f3f691b24f9","policy_revision":2,"local_metadata":{"host":{"name":"docker-fleet-agent"}}}
2023/07/24 04:25:03 DEBUG Policy revision assigned to the agent (ID: 62a3c8fc-7c19-4f0d-8fa9-e87913e7ed5c)...
2023/07/24 04:25:03 DEBUG checking for expected data in data stream...
2023/07/24 04:25:03 DEBUG found 0 hits in metrics-nginx.stubstatus-ep data stream
2023/07/24 04:25:04 DEBUG found 0 hits in metrics-nginx.stubstatus-ep data stream
2023/07/24 04:25:05 DEBUG found 0 hits in metrics-nginx.stubstatus-ep data stream
2023/07/24 04:25:06 DEBUG found 0 hits in metrics-nginx.stubstatus-ep data stream
2023/07/24 04:25:07 DEBUG found 0 hits in metrics-nginx.stubstatus-ep data stream
2023/07/24 04:25:08 DEBUG found 0 hits in metrics-nginx.stubstatus-ep data stream
2023/07/24 04:25:09 DEBUG found 0 hits in metrics-nginx.stubstatus-ep data stream
2023/07/24 04:25:10 DEBUG found 0 hits in metrics-nginx.stubstatus-ep data stream
2023/07/24 04:25:11 DEBUG found 0 hits in metrics-nginx.stubstatus-ep data stream
2023/07/24 04:25:12 DEBUG found 0 hits in metrics-nginx.stubstatus-ep data stream
2023/07/24 04:25:13 DEBUG found 0 hits in metrics-nginx.stubstatus-ep data stream
````
**How to fix this issue?** :  Use ES Stack version 8.8.2

**Does system test run successfully with multi-variant work, without TSDB enablement?** : Yes

**Command output after using ES version 8.8.2***
```
--- Test results for package: nginx - START ---
╭─────────┬─────────────┬───────────┬───────────────────────┬────────┬───────────────╮
│ PACKAGE │ DATA STREAM │ TEST TYPE │ TEST NAME             │ RESULT │  TIME ELAPSED │
├─────────┼─────────────┼───────────┼───────────────────────┼────────┼───────────────┤
│ nginx   │ stubstatus  │ system    │ default (variant: v1) │ PASS   │ 25.690394538s │
│ nginx   │ stubstatus  │ system    │ default (variant: v2) │ PASS   │ 20.010254478s │
╰─────────┴─────────────┴───────────┴───────────────────────┴────────┴───────────────╯

```

**Existing Issue**

- MySQL has two entries in variants.yml file. Because of this, [TSDB enablement for the MYSQL integration](https://github.com/elastic/integrations/pull/6968) package fails if `8.8.0` is used. Hence, `8.8.2` had to be used for TSDB enablement.

This issue may not be related to `elastic-package`. But, creating the issue here as the reason for this behaviour is related to how elastic-package works when TSDB is enabled in Elasticsearch.  

**Open Question**
Should all integration packages be updated to `8.8.2` to eliminate errors that may occur in future?

**Comment by lalit-satapathy** [comment]
>How to fix this issue? : Use ES Stack version 8.8.2

Did we conclude, what has changed in 8.8.2 to fix this issue?

**Comment by agithomas** [comment]
Here below are the details, based on my findings after going through the internal implementation of `elastic-package` tool. 

When there exist multiple variants, at the end of running of the system test of the first variant, elastic-package makes the below call to clear the records. 

```
POST /.ds-metrics-nginx.stubstatus-default-2023.07.24-000001/_delete_by_query?pretty
{ "query": { "match_all": {} } }
```

If the Elasticsearch version is 8.8.0, after this operation, no new documents get indexed. I could reproduce this issue with Integrations as well. @martijnvg , can you confirm if this is a known issue with 8.8.0?

From 8.8.1 and above version of Elasticsearch, after deleting the documents with the POST API call, the new document gets indexed. 

As a solution, we can upgrade to 8.8.1. It need not be 8.8.2.

**Comment by jsoriano** [comment]
@agithomas to be clear, packages being tested with stack versions >= 8.8.2 can be tested with variants and TSDB, right?

**Comment by agithomas** [comment]
> @agithomas to be clear, packages being tested with stack versions >= 8.8.2 can be tested with variants and TSDB, right?

Yes, correct.

**Comment by agithomas** [comment]
Closing the issue as no further action is needed.
