### ISSUE TITLE
Enrich Data and Policies bundled in Packages ?

### ISSUE THREAD

**Issue by nicpenning** [elastic/elastic-package#1375]
Is it possible to ingest a dataset into an index that will be used for an enrich policy when a package gets installed? Ingest pipelines would then be used to enrich data.

I have a great use case for DHCP where I enrich the events from the first part of the MAC with the vendor information. There are a lot of MAC addresses to vendor mappings so storing all of this information inside of a pipeline is pretty heavy.

**Comment by jsoriano** [comment]
Hey @nicpenning, there is no support for enrichment policies at the moment, but we have an open issue for this, here: https://github.com/elastic/package-spec/issues/292, you can take a look here, please consider adding your use case there. I will close this issue as duplicate.

**Comment by nicpenning** [comment]
Great,  thanks!
