### ISSUE TITLE
Add logstash as a component in the stack boot up by elastic-package 

### ISSUE THREAD

**Issue by mrodm** [elastic/elastic-package#1432]
It could be added logstash as a new component/service in the Elastic stack boot up by elastic-package to be able to test different scenarios.

This logstash should not be started by default. It should be started and configured optionally (using a new parameter in `stack up`?).

This logstash could be configured optionally in the elastic-agent (as an output) and it should be configured Elasticsearch as an output of this logstash. Doing so, the documents sent by the elastic-agent are ingested using logstash. This could leverage the testing to test new scenarios where there are more fields present in the document, for instance `event.original` (based on  https://github.com/elastic/integrations/issues/3451#issuecomment-1693521101).

**Comment by bhapas** [comment]
@mrodm @jsoriano 

Just trying to summarise the solution thought for a discussion

- A new [profile Config option](https://github.com/elastic/elastic-package/blob/d75f2535bb730a186018eb96ee03f73260a7fbc3/internal/stack/resources.go#L125) to be added - `stack.logstash_enabled` which takes a bool in the form of string
- Add logstash to the [docker-compose template file](https://github.com/elastic/elastic-package/blob/d75f2535bb730a186018eb96ee03f73260a7fbc3/internal/stack/_static/docker-compose-stack.yml.tmpl)
 Not sure if we can enable/disable a service (logstash in this case) based on a bool config - Probably using [profiles with compose](https://docs.docker.com/compose/profiles/)
- Alternatively, Add another `docker-compose-stack-logstash.yml.tmpl` file with logstash in it and conditionally load the template file [here](https://github.com/elastic/elastic-package/blob/main/internal/stack/resources.go#L65)
- To start with, a hardcoded `logstash.conf.tmpl` file with default output being `elasticsearch` and a basic filter plugin for [elastic_integration](https://github.com/elastic/logstash-filter-elastic_integration/tree/main) , but would be ideal if we can inject user config for logstash based testing [ Did not arrive at a concrete solution for this. Happy to hear ].
- Configure the output of elastic agent to be `logstash`.

Please feel free to comment on one or all the points above and I would also like to get an opinion from logstash team for the docker compose logstash setup , once the PR is ready.

**Comment by bhapas** [comment]
Fixed in #1458
