### ISSUE TITLE
Integrations config should be rendered at build time

### ISSUE THREAD

**Issue by jlind23** [elastic/elastic-package#1469]
In order to ease the adoption of Elastic Agent standalone, integrations configuration should be easily discoverable/usable without having to install them in Kibana.
In order to solve this, elastic-package build step should render all stream HBS files, preserve code comments and divide config by data stream.
After these files will be considered as assets of packages.

More info in https://github.com/elastic/ingest-dev/issues/2456

**Comment by jsoriano** [comment]
Could we have an example of the expected input and output?

**Comment by kpollich** [comment]
Closing as no longer relevant
