### ISSUE TITLE
Tests fail due to ECS expected values

### ISSUE THREAD

**Issue by chrisberkhout** [elastic/elastic-package#1472]
Expected values defined for an ECS field, such as [for `threat.indicator.type`](https://github.com/elastic/ecs/blob/main/schemas/threat.yml#L390-L414), are not the only valid values ([def](https://github.com/elastic/ecs/blob/main/schemas/README.md?plain=1#L169), emphasis added):
> expected_values (optional): An array of expected values for the field. Schema consumers can validate integrations and mapped data against the listed values. These values are the recommended convention, but **users may also use other values**.

The `expected_values` field was intended to indicate the "SHOULD" requirement level (as [defined](https://www.ietf.org/rfc/rfc2119.txt) for RFCs). For this level it may be appropriate to warn about the use of other values, but not to fail a build or test run.

Currently, pipeline and system tests will fail if they find values other than the expected ones.

A previous workaround when using ECS dynamic mappings was to override with explicit definitions. That makes tests pass now if those definitions include the full set of values or an empty array ([example](https://github.com/chrisberkhout/elastic-integrations/commit/de308a50f430f77cbaf9e23caa57de2d8c707f4d)), but now `elastic-package` will not successfully build a package if it defines its own `expected_values`, so this workaround no longer works.

Some related links:
* [Slack discussion from when the workaround still worked](https://app.slack.com/client/T0CUZ52US/C010LT16CFR/thread/C010LT16CFR-1692886299.240509)
* [Code that does the validation](https://github.com/elastic/elastic-package/blob/4aa4b7/internal/fields/validate.go#L888-L890)
* [PR introducing that code](https://github.com/elastic/elastic-package/pull/865)
* [Some changes to `validate.go` earlier this year, regarding import of the ECS schema](https://github.com/elastic/elastic-package/pull/1090/files#diff-36d325d58b4ea8957abc63576d2e04d30ec8e58435ba06d442cb7923af063ad3)
* [A recent ECS validation PR](https://github.com/elastic/elastic-package/pull/1452)
* [New integration PR blocked by the need to check, build and test with non-expected values for and `threat.indicator.type` and `threat.indicator.name` (although `threat.indicator.name` is a misuse of expected values and will be converted to examples)](https://github.com/elastic/integrations/pull/7385)

**Comment by chrisberkhout** [comment]
As discussed today with @andrewkroh and @P1llus, and earlier with @kgeller and @ebeahan.

**Comment by jsoriano** [comment]
Thanks for the detailed description.

> The `expected_values` field was intended to indicate the "SHOULD" requirement level (as [defined](https://www.ietf.org/rfc/rfc2119.txt) for RFCs). For this level it may be appropriate to warn about the use of other values, but not to fail a build or test run.

By now I would stay on the restrictive side of things. I don't see other packages using `expected_values` in integrations.

In any case, it sounds good to allow to define `expected_values` per field. I am opening https://github.com/elastic/package-spec/pull/616 by now to support that.

Also, once https://github.com/elastic/package-spec/issues/558 is done, we can also add support to selectively disable this validation.

**Comment by chrisberkhout** [comment]
IMHO breaking a build due to a valid though not expected value is something I'd rather opt into than have as default.

It's not critical for me now since I found a variation on my earlier workaround that still works.
