### ISSUE TITLE
Command: export Kibana assets

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-package#148]
New package developers will create assets such as visualizations, dashboards, etc. in Kibana for their packages. Then they will need to export these assets as JSON files from Kibana. 

We should provide a sub-command that does the following:
- Talks to Kibana and exports the relevant assets for the package.
- Creates the appropriate asset files in appropriate locations in the package.
- Prefixes each asset ID (including its references in other asset files) with the package name, all lowercased.

**Comment by mtojek** [comment]
Related: https://github.com/elastic/elastic-package/issues/12

**Comment by mtojek** [comment]
I'm going with this issue.
