### ISSUE TITLE
Feature: run pipeline tests

### ISSUE THREAD

**Issue by mtojek** [elastic/elastic-package#15]
Master issue: https://github.com/elastic/elastic-package/issues/14

Pipeline tests are quick, small tests that can verify the ingest pipeline without a need for booting up the entire cluster (only the Elasticsearch instance).

Input:
`test-a-events.json`: defines a set of JSON events, which could be produced by the input. These input data are sent to the pipeline.
`test-a-expected.json`: contains a document expected to be produced by the tested pipeline

Execution:

The test runner (elastic-package) installs the ingest pipeline in Elasticsearch, sends mocked events to the pipeline and compares stored documents with the expected output.

**Comment by ycombinator** [comment]
@mtojek I started working on a PR for this but didn't get too far. Please go ahead and work on it if you have time! I've removed my assignment.

**Comment by mtojek** [comment]
I'm going with this now.
