### ISSUE TITLE
Automatically create sample_event.json

### ISSUE THREAD

**Issue by mtojek** [elastic/elastic-package#150]
The `sample_event.json` file contains a representative sample of documents stored in data stream.

The goal of this task is to research and design an automatic approach to collect sample events.

**Comment by ycombinator** [comment]
WDYT about creating these files when `elastic-package test system --generate` is run? Currently this command just runs the system tests without generating any files (i.e. same as running `elastic-package test system`).

**Comment by mtojek** [comment]
I think this is the only moment when we can do this (during system tests) :) Please go for it.

**Comment by ycombinator** [comment]
I'm going with this now.
