### ISSUE TITLE
Add support for Logstash service in system benchmarking

### ISSUE THREAD

**Issue by ebeahan** [elastic/elastic-package#1534]
With the Logstash service added in #1458, system benchmarking should also support using the logstash-output in the benchmarking agent policies.

Like done for [system testing](https://github.com/elastic/elastic-package/blob/main/internal/testrunner/runners/system/runner.go#L559), if `stack.logstash_enabled: true` is set in the current profile's config use the logstash output over the default.

**Comment by ebeahan** [comment]
Also handing the ingest node stats will be different. Unsure what metrics/stats are exposed in Logstash compared to ES ingest node stats.

**Comment by bhapas** [comment]
#1615 adds support for logstash in system benchmarking. Logstash does not support metrics similar to ingest node yet. Hence closing this issue.

**Comment by bhapas** [comment]
Issue created on logstash elastic integration filter plugin to resolve this. https://github.com/elastic/logstash-filter-elastic_integration/issues/119
