### ISSUE TITLE
Forwarding ports and volume mounts?

### ISSUE THREAD

**Issue by andrewstucki** [elastic/elastic-package#155]
So right now the default behavior for `elastic-package stack up` is to create an agent running in docker. In manually verifying the behavior of various packages, it requires me to go in and modify `~/.elastic-package/stack/snapshot.yml` to add a bunch of port bindings and volume mounts if I want to do something like test a syslog/UDP/TCP/file input. I figure it might be helpful to do some of these by default or throw them behind a switch.

**Comment by mtojek** [comment]
Thank you for the issue, Andrew.

Could you please provide us more details and describe a single use case (refer to real package, write down actions you're doing)? I believe it's possible to extend system tests with new features (/cc @ycombinator ).

**Comment by mtojek** [comment]
Duplicate of https://github.com/elastic/elastic-package/issues/179
