### ISSUE TITLE
[Rally] Not able to run benchmarks locally 

### ISSUE THREAD

**Issue by ali786XI** [elastic/elastic-package#1587]
- While running the `rally` tool, observed that the flag `--package-from-registry` is required to be passed when running the tool. However, if one needs to read benchmarks file from local package folder then it is not happening as facing below error.

Command:- `elastic-package benchmark rally --benchmark <data_stream>-benchmark -v`
Error:- `Error: getting package name and version failed, expected format: <package>-<version>: package name and version from registry not valid ()`

**Comment by aspacca** [comment]
fix in #1588 , @jsoriano can you review? thanks
