### ISSUE TITLE
Bug: redeploy package-registry on the live Elastic up

### ISSUE THREAD

**Issue by mtojek** [elastic/elastic-package#160]
Steps to reproduce:

```
$ elastic-package stack up --services=elasticsearch -d
$ elastic-package stack up --services=package-registry -d
```

The second command restarts the entire stack, but shouldn't.

**Comment by ycombinator** [comment]
I just ran `elastic-package stack up --services=package-registry -v` and the only container I have running now is the `package-registry`. Am I misunderstanding this bug?

**Comment by mtojek** [comment]
Please to boot up Elasticsearch and then add the package-registry to the stack.

**Comment by ycombinator** [comment]
Yes, sorry, I completely missed the first step 🤦 .

**Comment by mtojek** [comment]
I see this as a blocker for redeploying changes while developing a new package (currently the restart of package-registry is required).

**Comment by ycombinator** [comment]
I think you can generalize this bug. Booting up any component(s) of the stack destroys all previously-running components. I assume the desired behavior should be additive?

**Comment by mtojek** [comment]
Yes or no.

If you redeploy Kibana without redeploying Elasticsearch, it simply won't work (due to encryption?).
