### ISSUE TITLE
Pipeline test returns test case failure if pipeline sets error.message

### ISSUE THREAD

**Issue by ca-dane-jones** [elastic/elastic-package#1622]
I have several cases where I'm extracting specific error messages from events and populating a document's error.message field.  Any time an error.message is set on a document, `elastic-package test pipeline` and `elastic-package test pipeline -g` return "unexpected pipeline error" and test case failures.

**Sample output:**
Run pipeline tests for the package
--- Test results for package: postfix - START ---
FAILURE DETAILS:
postfix/log test-smtp.log:
[0] unexpected pipeline error: Host or domain name not found. Name service error for name=192.168.1.1.redacted.zen.dq.spamhaus.net type=A: Host not found, try again
[1] unexpected pipeline error: error:0A0000C1:SSL routines::no shared cipher:../ssl/statem/statem_srvr.c:2220:
**...**
--- Test results for package: postfix - END   ---
Done
Error: one or more test cases failed

**Pipeline YAML Excerpt**
```
---
processors:
  - grok:
      field: message
      patterns:
          - 'warning: (?<error.code>TLS library problem): %{GREEDYDATA:error.message}'
```

**Log Line**
warning: TLS library problem: error:0A0000C1:SSL routines::no shared cipher:../ssl/statem/statem_srvr.c:2220:

**Comment by jsoriano** [comment]
Ah yes, this is probably the same issue as in https://github.com/elastic/elastic-package/issues/1392, at the moment `error.message` can only be used to indicate errors in the ingestion, not to store event data.

I will close this by now as duplicate. Thanks for reporting!
