### ISSUE TITLE
Integrate OpenTelemetry Agents into elastic-package

### ISSUE THREAD

**Issue by 111andre111** [elastic/elastic-package#1648]
Hi folks,
I have a question. Wouldn't it make sense to integrate OpenTelemetry agents inout elastic-package?
That would match to our strategy we want to do more with OpenTelemetry agents.

**Comment by jsoriano** [comment]
Hey @111andre111,

`elastic-package` is intended to be a tool for package development, what would be the purpose of OpenTelemetry there?

I guess we will have OpenTelemetry-based integrations at some point but till this is clear I don't know what would be the benefit of having OpenTelemetry for packages development.

**Comment by kpollich** [comment]
I don't think this is actionable in its current state. The ongoing OTel integrations project may touch `elastic-package`, but there's nothing concrete planned in that way currently. Closing this. Feel free to reopen if there's more to discuss.
