### ISSUE TITLE
test install: Test if package can be installed

### ISSUE THREAD

**Issue by mtojek** [elastic/elastic-package#166]
This issue hasn't been detected in integrations: https://github.com/elastic/integrations/pull/392 , but only in the package-storage.

We can improve on that and introduce another test runner: `test install` which can replicate the TestIntegration behavior from the package-storage.

**Comment by ycombinator** [comment]
Do you think the steps that `elastic-package test install` would take would be similar to `elastic-package install` (https://github.com/elastic/elastic-package/issues/8)? If so, I wonder if we need a separate `elastic-package test install` sub-command or if we can just run `elastic-package install` from the appropriate `make/mage` targets.

**Comment by mtojek** [comment]
Let me challenge this -

in general these commands are related to each other. On the other hand the `elastic-package install` can be used to install the package in Kibana and leave it there (installed). I would expect from `elastic-package test install` to install the package and then try to clean used resources (uninstall?).

**Comment by mtojek** [comment]
Just confirmed with @skh, there is DELETE method available, which can uninstall the package.

**Comment by ycombinator** [comment]
Fair point. Let's go ahead with this test. 👍

**Comment by ruflin** [comment]
I guess as soon as this lands, `elastic-package` can replace almost all the code in https://github.com/elastic/package-storage/blob/snapshot/testing/main_integration_test.go ?

**Comment by mtojek** [comment]
@ycombinator I think we can close this issue in favor of `test asset`, which doesn't only verify if the package can be installed, but also checks single assets.

**Comment by ycombinator** [comment]
++ @mtojek, closing this since the functionality is covered by `elastic-package test asset`.

Note that we may still separately want a `elastic-package install` command, which is already being tracked in https://github.com/elastic/elastic-package/issues/8.
