### ISSUE TITLE
Align more tests for elastic-package to Build Kite / "/test" in GitHub

### ISSUE THREAD

**Issue by nicpenning** [elastic/elastic-package#1721]
After the tests have moved to build kite in GitHub, it is a challenge for those who do not have permissions to run /test now also cannot not see the build failure messages. This lengthens the amount of time for community members or those who cannot see the failed build error messages in a tough spot to always be asking someone with permission to see what the errors are so either party can resolve.

A recent example on an integration (https://github.com/elastic/integrations/pull/8993) :
![image](https://github.com/elastic/elastic-package/assets/5582679/396e239c-85c7-40d6-b8f0-ed625fc0b188)

Some other errors that I had to glean from Elastic maintainers are:

`Error: can't install the package: could not zip-install package; API status code = 500; response body = {"statusCode":500,"error":"Internal Server Error","message":"Migration function for version 7.11.0 threw an error"}
[cisa_kevs] run_tests_package failed`

`Error: there is no owner for "packages/cisa_kevs" in ".github/CODEOWNERS"`

`Error: owner "elastic/integrations" defined in "packages/cisa_kevs/manifest.yml" is not in ".github/CODEOWNERS"`

Each of those were found in separate /test and it would be great to have these checks locally before expending other peoples time and increasing the amount of bottlenecks to integration development.

Ideally, it would be great to have all tests completed so the chance of success in the publication of an integration in GitHub is much greater.

**Comment by jsoriano** [comment]
@nicpenning is this still needed once that https://github.com/elastic/integrations/issues/9357 has been solved?

> Error: can't install the package: could not zip-install package; API status code = 500; response body = {"statusCode":500,"error":"Internal Server Error","message":"Migration function for version 7.11.0 threw an error"} [cisa_kevs] run_tests_package failed

This error should be locally detectable by running tests.

> `Error: there is no owner for "packages/cisa_kevs" in ".github/CODEOWNERS"`
> 
> `Error: owner "elastic/integrations" defined in "packages/cisa_kevs/manifest.yml" is not in ".github/CODEOWNERS"`

We could try to add github codeowners validation to `elastic-package check`, but not sure about this because the policy may depend on the repository.

**Comment by jsoriano** [comment]
I'd say to wait some days after having https://github.com/elastic/integrations/issues/9357, and we can revisit this to see what papercuts need more attention.

Thanks for the feedback!

**Comment by jsoriano** [comment]
Hey @nicpenning, buildkite builds should be visible again. Have you been missing being able to run tests?

**Comment by nicpenning** [comment]
It appears that way, yes! Thank you very much!

**Comment by jsoriano** [comment]
Ok, closing this by now, thanks for the feedback!
