### ISSUE TITLE
[Feature request] Optionally disable latest release check at startup

### ISSUE THREAD

**Issue by Oddly** [elastic/elastic-package#1772]
By default, `elastic-package` does a check to Github.com, to see if this release is the latest. In our environment, this adds a significant latency (timeout) to the normal build commands.
One way I can think to address this is to disable the check (possibly with a flag or config option), or be able to set a custom timeout option.

**Comment by jsoriano** [comment]
Hey @Oddly,
In principle you can disable this check by setting the environment variable `ELASTIC_PACKAGE_CHECK_UPDATE_DISABLED=1`.

I will close this issue, please reopen if this solution doesn't work or is not enough for your case.

**Comment by Oddly** [comment]
Thanks, that does exactly what I want.
