### ISSUE TITLE
Let me change container ports and other settings

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/elastic-package#179]
So, right now I use a remote docker host (_remote_ meaning a server in my closet) for all my for all my development, since docker4mac is still terrible. This works great, but it means that any container that exposes some service needs to expose it _publicly_:

```
     ports:
       - "0.0.0.0:5601:5601"
```

`elastic-package` doesn't seem to like me doing that, as it keeps the config in `~/.elastic-package` and it'll blow away any changes I make at will. I don't really feel like mainting my own `.yml` either. Perhaps we can have `elastic-package` maybe read some port override from an environment variable or custom dotfile?

**Comment by mtojek** [comment]
@ycombinator we need to think about a convenient API to cover this suggestion.

**Comment by ycombinator** [comment]
How about two new commands:

`elastic-package stack config show`
set <setting name> <setting value>`.

**Comment by ycombinator** [comment]
We could use environment variables but I think that could get a bit unwieldy if the number of user-settable settings grows beyond a handful. 

So instead, borrowing from `kubectl`, how about introducing the following new sub-commands.

### API

* `elastic-package stack config show` or `elastic-package stack config view`. This command will print out the list of settings that can be configured and their current values.
* `elastic-package stack config set <setting name> <setting value>`. This command will set a single setting, thus overriding its default value.
* `elastic-package stack config unset <setting name>`. This command will unset a single setting.

### Example Usage

* `elastic-package stack config set kibana.port.public 6701`: sets the public (exposed) port to 6701.

### Implementation

* There is a new internal file somewhere under `~/.elastic-package/stack`, say `~/.elastic-package/stack/settings.yml`. It contains any stack-related settings that can be set (i.e. overridden) by the user. By default the file is empty, so settings that are "hardcoded" are used instead.
* Running `elastic-package stack config set <setting name> <setting value>` sets the given setting in `~/.elastic-package/stack/settings.yml`.
* Running `elastic-package stack config unset <setting name>` removes the given setting from `~/.elastic-package/stack/settings.yml`.
* Running `elastic-package stack config show` shows _all_ possible user-settable settings and their current values. This means starting with the "hardcoded" default values for each setting, then overlaying any values for that setting from  `~/.elastic-package/stack/settings.yml`, then displaying the results.
* When `elastic-package stack up` is run, the contents of `~/.elastic-package/stack/settings.yml` are overlaid on the "hardcoded" default values for settings, and the results are used when booting up the stack.

### Question

* If a user runs `elastic-package stack config set <setting name> <setting value>` or `elastic-package stack config unset <setting name>` while the stack is already running via `elastic-package stack up` do we automatically reboot the stack for them? Or do we just inform them that they need to reboot it? Or something else?

**Comment by ycombinator** [comment]
(Sorry, I closed this issue by accident. I have reopened it now.)

**Comment by mtojek** [comment]
I like this way of accessing configuration options, but the user needs to remember that all settings will be reset if the stack directory is removed.

> If a user runs elastic-package stack config set <setting name> <setting value> or elastic-package stack config unset <setting name> while the stack is already running via elastic-package stack up do we automatically reboot the stack for them? Or do we just inform them that they need to reboot it? Or something else?

Let's start with the basic approach, so the entire stack needs a reboot. It will be already a hard task to find all these dependencies. Alternatively you can try to get rid of the `stack` directory and build it every time in runtime or the elastic-package will automatically recreate the stack if it detects a change.

Did you consider introducing any mode that will adjust the config options accordingly to the integration? Let's say that the integration needs an additional mount or exposed volume (see https://github.com/elastic/elastic-package/issues/155). Maybe it's possible to implement sth like `.stackrc.json` (similarly to `.vimrc` or `.yarnrc`) and put it inside the integration?

**Comment by ycombinator** [comment]
> ... but the user needs to remember that all settings will be reset if the stack directory is removed.

Good point. I think there are two cases here:
- either they remove it manually, in which case they are shooting themselves in the foot a bit so I'm okay with this causing a reset.
- or they run `elastic-package clean`, in which case we can control what files are removed so we can keep the config file.

> Let's start with the basic approach, so the entire stack needs a reboot.

IIUC, you are saying we go with the "just inform them that they need to reboot it" suggestion. Is that right?

> Did you consider introducing any mode that will adjust the config options accordingly to the integration? 

I did not consider this and it is an interesting idea. IIUC, this would result in the following precedence order for stack settings:  default (hardcoded) settings < settings set via `elastic-package stack config set` < per-integration settings. Correct? If so, I think the tricky part would be that we may need to reconfigure and therefore reboot the stack for every integration, if that integration defines custom settings.

Maybe we should break up the implementation into two PRs so we can deliver incremental progress on these two use cases?
1. (#179) Implement `elastic-package stack config` feature, and then
2. (#155) Implement per-integration settings feature.

**Comment by mtojek** [comment]
Maybe we should break up the implementation into two PRs so we can deliver incremental progress on these two use cases?

> Yes, we should definitely make it as granular as possible.

**Comment by ycombinator** [comment]
I'm going to start working on this issue, starting with the first part:

> Implement `elastic-package stack config` feature.

**Comment by ycombinator** [comment]
Chatting with @fearful-symmetry off-issue, they were planning on working on this so un-assigning myself.

**Comment by mtojek** [comment]
@fearful-symmetry It would great to see some really brief proposal or GH comment, what is your idea to solve this case.

**Comment by fearful-symmetry** [comment]
@mtojek yep, was discussing with @ycombinator a bit.

So, with the system integration, there's often a need to retool the docker and kibana setup to support different testing environments. At most I need to change the port exposure settings, since I use an external docker server, so `127.0.0.1` won't work for the ES/Kibana ports. However, if I need to run the agent on a random VM or other external host to test a specific OS, I might need to tinker with other settings as well. In addition, if this repo makes changes to whatever lives in ~/.elastic-package/stack`, my configs will get overwritten. So, I was thinking we need some kind of profile management system to manage the config, like...

```
elastic-package cfg new --from default my_profile
elastic-package stack --cfg my_profile up
elastic-package cfg new updated_cfg
```

Or something like that. This will move the configs that live in the `stack` directory (`Dockerfile.package-registry  kibana.config.yml  package-registry.config.yml  snapshot.yml`) to their own directories named after the profiles. A `new` profile can either grab the latest config (not sure what the logic is right now for initially populating that directory), or just copy over an existing config. We might also want to use this as an opportunity to offload some of the cruft that ends up in the CLI, for example, if I have a special profile for testing against an external VM, there's a 100% chance that I'll also run `--services elasticsearch,kibana,package-registry` since I don't need the agent container.

**Comment by mtojek** [comment]
@fearful-symmetry did you have a chance to work on this issue? If so, could you please share the status update?

We're working on backlog prioritization and can look for some spare time to cover this issue if you're busy.

**Comment by fearful-symmetry** [comment]
@mtojek I'd still like to work on this, but I'm also probably going to be pretty busy through the next week. Does the proposal itself sound good?

**Comment by mtojek** [comment]
Yes, I like the idea of profiles. I was wondering whether the configuration should be limited to stack only or to the application in-general (so we can use it also for other purposes, e.g. change linting behavior, enable beta-features?).

**Comment by fearful-symmetry** [comment]
Yah, that's a possibility. We might end up with sort of a shell-like config hierarchy, where there's a global `.config` file, then a variety of user/profile-level configs.

**Comment by mtojek** [comment]
@fearful-symmetry Do you plan to follow up on this issue?

**Comment by fearful-symmetry** [comment]
@mtojek 

Yep, planning on a second PR with the feature. Some features for 7.13 are currently taking priority, as the FF is next week.

**Comment by mtojek** [comment]
@fearful-symmetry I think you can close this issue now.
