### ISSUE TITLE
Add units and metric type to fields docs

### ISSUE THREAD

**Issue by exekias** [elastic/elastic-package#181]
`elastic-package` build is able to get the docs template and create the final package `README.md`.

One of the things it does is injecting `fields` blocks for each data stream. With https://github.com/elastic/package-spec/issues/42 in, it would be good to add a column for Units in all cases, and a column for Metric type for the data streams of type `metrics`.

Example PR adding these fields: https://github.com/elastic/integrations/pull/402

**Comment by mtojek** [comment]
Let's try to move this forward.
