### ISSUE TITLE
Add negative tests for detection of issues in elastic agent logs

### ISSUE THREAD

**Issue by jsoriano** [elastic/elastic-package#1811]
`elastic-agent` supports finding issues in Elastic Agent logs. We have had some regressions and fixes around there, that could have been detected earlier by negative tests.

We should find a test case that can be used for negative tests. One challenge for this is that these issues use to be related to specific versions of the stack, and we always test now with the default version of the stack.

For example we know that prometheus package had issues in 8.12.0, but these issues were caused by a regression in the stack.

**Comment by mrodm** [comment]
This should be reproduced with the package `prometheus` from the integrations repository using Elastic stack 8.12.0 with this changeset : a2c55c4cbf752e0490

```
cd /path/integrations/repo
cd packages/prometheus
git co a2c55c4cbf752e0490

elastic-package stack up -v -d --version 8.12.0
elastic-package test system -v
elastic-package stack down -v
```
