### ISSUE TITLE
Fail tests if failure store contains any documents

### ISSUE THREAD

**Issue by flash1293** [elastic/elastic-package#1832]
The failure store is already available as an experimental feature in the 8.15 snapshot build of Elasticsearch.

While it's not ready yet to be enabled as a default feature for integrations, it can be used as an additiona layer of security, making sure no documents are dropped during system tests which would indicate an issue with the integration.

I propose the following steps:
* In stack version >=8.15, always enable the failure store on all data streams
* Similar to https://github.com/elastic/elastic-package/pull/1738, validate that a datastream under test didn't drop any documents in the failure store (fail the test in case it happens)
* Add a configuration option to the test config that allows skipping this check
* Document what the failure store means and how to skip the check

What do you think @ruflin @jsoriano ? It seems like this can be done even before the failure store is ready to be used on customers clusters.

**Comment by jsoriano** [comment]
Yes, I think we could try it in elastic-package even if it is not ready for GA.

**Comment by ruflin** [comment]
++ on enabling it for the tests and check if any documents end up in it.

**Comment by jsoriano** [comment]
@flash1293 @ruflin do you know where can I find documentation about how to use the failure store?

**Comment by ruflin** [comment]
Here is a gist to get you started: https://gist.github.com/jbaiera/cecf6b973c0a15e72e2b189120caba51 Note, some of the APIs still might change.

@jbaiera Are there already some more official docs somewhere?

**Comment by jsoriano** [comment]
@flash1293 @ruflin I have been playing a bit with the failure store and I think that the way it is enabled is a bit problematic for its use while testing packages.

It is enabled by setting `failure_store` to `true` in the index template for the data stream. This setting has to be set inside `data_stream`, like this:
```
PUT _index_template/my-index-template
{
  "index_patterns": ["my-index-template-*"],
  "data_stream": {
    "failure_store": true
  }
}
```

But when using packages, customization of index templates is based on component templates, and component templates don't allow to set `data_stream` (or I haven't managed to do it), so we cannot selectively enable it on specific data streams or packages.

I see some paths forward for this:
* Adding support in Elasticsearch to enable the failure store in existing data streams. For example with something like `POST my-data-stream/_rollover?enable_failure_store=true`. I think this would be quite valuable in testing or debugging scenarios, where the user may not have enabled the failure store beforehand, but wants to look for failures in future ingestions. cc @jbaiera
* Adding support in Fleet to enable the failure store when it creates the index templates. This could be based for example in a setting in Kibana that we enable in development environments, and maybe the users can toggle in the future. I guess something like this is what we will need in the long term. cc @kpollich
* Make elastic-package to update index templates after installing packages. This is a bit hacky, but could work by now to unblock this task. I will try this approach while we evaluate other options.

**Comment by flash1293** [comment]
Good callout @jsoriano , I think eventually we want to allow integration authors to control failure store configuration as a setting of the data stream, so we could also build out this flow (extending package spec and implementing it conditionally on the Kibana side) and enforce it being set to true for the system tests. Mostly suggesting this because it seems like we won't have to throw anything of the implementation away later and it doesn't seem like much more work.

**Comment by jsoriano** [comment]
> I think eventually we want to allow integration authors to control failure store configuration as a setting of the data stream

Do you mean that for the final usage? I am not sure about that. With this, there would be two kinds of error handling, what can be confusing for users and support. Final users won't know if a failure store is being used for a given integration unless something else is built in Kibana to very explicitly show documents there. I think package developers should rather rely on `on_failure` handlers if they expect cases where the pipeline can fail.

Or do you think this can provide something else beyond an alternative error handling?

As I see it:
* We enable the failure store for system tests as a more reliable way to detect unhandled failures. We don't provide a escape-hatch for developers. Package developers should use `on_failure` when they know that certain cases can produce errors. To enable this, ideally something is added to Elasticsearch or Fleet so elastic-package doesn't need to modify index templates. 
* Eventually we provide a escape-hatch for users that know what they are doing, by adding an advanced toggle to enable the failure store per data stream.
* Package developers don't have any way to decide when the failure store is enabled or not.

**Comment by flash1293** [comment]
> Or do you think this can provide something else beyond an alternative error handling?

Yeah, I expected this to be a secondary layer of safety (ideally enabled by default rather than opt-in, but that can come later). We should still set `on_failure` handlers correctly, because data in the failure store is not usable at all, it's mostly to get the data collection back on track.

It's to help users if something goes wrong, even though we try hard that it doesn't.

> Final users won't know if a failure store is being used for a given integration unless something else is built in Kibana to very explicitly show documents there

That would be the dataset quality page, where we want to add support for failure store information.

**Comment by ruflin** [comment]
An additional option here is that Elasticsearch can be started with failure store enabled by default for all `logs-*-*`, `metrics-*-*` etc. data streams. For now, this would be used for testing like this only on startup a flag has to be passed into Elasticsearch. I expect eventually this to become also the default.

For the `on_failure` handler, I think it is important that this is used for the "known" error cases. At the moment it is also used for general cases AFAIK because the failure store did not exist so far.

**Comment by jsoriano** [comment]
I am executing in https://buildkite.com/elastic/integrations/builds/13667 the current integrations as they are, with the failure store enabled, several integrations failed with errors like this one:
```
there are 1 documents in the failure store with errors: [QuZK4rUG69Ss32vYI+qe65msnVU=]: version conflict, document already exists (current version [1])
```
Does anyone know why something may be trying to ingest with the same document id?

This is the PR with the changes in elastic-package: https://github.com/elastic/elastic-package/pull/1973

**Comment by jsoriano** [comment]
Ok, it looks like the packages having conflicting documents are explicitly writing the `_id` field, using the `fingerprint` processor. So I guess we should filter out these errors.

**Comment by jsoriano** [comment]
> `es.failure_store_feature_flag_enabled: true`

Correction, this flag neither works in 8.15. Is there any user facing feature flag to enable the failure store? Will the feature be available in 8.15 GA versions?

**Comment by jsoriano** [comment]
It seems to work when used as system property, with `-Des.failure_store_feature_flag_enabled=true`.

**Comment by jsoriano** [comment]
@flash1293 I have opened https://github.com/elastic/elastic-package/pull/1973 for review, it'd be great if you could give it a try. Thanks!

**Comment by ruflin** [comment]
Interesting find around the _id overwrite: https://github.com/elastic/elastic-package/issues/1832#issuecomment-2228714103 @jbaiera @dakrone I wonder what should happen in this scenario. Should this really go into the failure store 🤔

**Comment by dakrone** [comment]
Hmm… I can see arguments for either way. On one hand, the user has explicitly asked for the document to be rejected if the versioning doesn't match, but on the other hand, the document _could_ be different and then that document is "lost" (not really lost, but rejected by ES).

I think I lean slightly towards treating version conflicts as something that does _not_ go into the failure store, but I'd like to hear from others on the Observability side whether that would be reasonable. @ruflin, @flash1293, @felixbarny et al, do you have an opinion?

**Comment by cmacknz** [comment]
There have been several instances where incorrectly chosen TSDB dimensions have lead to version conflicts for documents that are not actually unique. Having a consistent and easily automated way to detect this via the failure store would be very useful.

At the same time, anyone using _id explicitly for de-duplication would not want version conflicts in the failure store because the point of de-duplication is not to waste resources storing the same document multiple times.

The compromise between those two scenarios is to make putting version conflicts in the failure store optional (defaulting to off), so that it can be turned on during development and used as a way to audit TSDB dimensions for correctness in integrations.

If it can't be made optional, I bias towards not putting them in the failure store so de-duplication use cases do what they are supposed to do.

**Comment by felixbarny** [comment]
To me, it also makes sense to not store version conflicts, including conflicts due to TSDB's duplicate detection, in the failure store. 

> turned on during development and used as a way to audit TSDB dimensions for correctness in integrations.

I don't think we need the failure store for that. We can just fail the tests if there are ingestion failures.
