### ISSUE TITLE
Fleet: Make subobjects: false the default for all data streams

### ISSUE THREAD

**Issue by flash1293** [elastic/elastic-package#1872]
**Describe the feature:** It's currently possible for data streams to opt into `subobjects: false` for data streams. As this is meant to be the default for logs streams in the future and also a sensible default for metrics, it should be the default for newly introduced data streams in integrations.

Also after releasing Package Spec 3.2.0, `subobjects: false` should be added to the archetypes of `elastic-package create` for data streams, so new packages created by this tool include it.

**Comment by flash1293** [comment]
Thinking this through, we should also set `subobjects: false` on metrics streams in the same way - it's even more common there and all the considerations still apply.

Should I create a separate issue for this or can it be handled as part of this one @jsoriano ?

**Comment by jsoriano** [comment]
> Thinking this through, we should also set `subobjects: false` on metrics streams in the same way - it's even more common there and all the considerations still apply.
> 
> Should I create a separate issue for this or can it be handled as part of this one @jsoriano ?

Lets keep it in the same issue so we define a common plan for both.

**Comment by flash1293** [comment]
Adjusted the description
