### ISSUE TITLE
Support stack with service mode

### ISSUE THREAD

**Issue by mtojek** [elastic/elastic-package#190]
Apparently we've forgotten about this mode as we're focused on the system test runner.

Use case:
A developer wants to run the Elastic stack and the service (like Apache) to design Kibana dashboards.

Temporary workaround:
Provide instructions to interact with the `docker` command to let the service connect to the stack.

Ideal solution:
`elastic-package stack` provides a subcommand to connect to the Elastic stack.

/cc @ycombinator @ChrsMark

**Comment by ycombinator** [comment]
++ we already have the information for spinning up the integration service (e.g. Apache), in `_dev/deploy` so this shouldn't be too difficult to build out by reusing parts of the implementation from the system test runner!

**Comment by mtojek** [comment]
It's not bad, it's just two commands :)

_(I assume that the Elastic stack is up and running, especially the Elastic Agent)._

Boot up the docker-compose with Apache:

```bash
SERVICE_LOGS_DIR=/Users/JohnDoe/.elastic-package/tmp/service_logs docker-compose -p elastic-package-service up -d
```

Connect Apache container to the `elastic-package-stack` network:

```bash
docker network connect elastic-package-stack_default elastic-package-service_apache_1
```

Verify in the Elastic Agent container (run from the Agent container):

```bash
curl http://elastic-package-service_apache_1:80/server-status -I
HTTP/1.1 200 OK
Date: Wed, 25 Nov 2020 11:49:58 GMT
Server: Apache/2.4.20 (Unix)
Content-Type: text/html; charset=ISO-8859-1
```

```bash
ls /tmp/service_logs/
access.log  error.log  httpd.pid
```

**Comment by mtojek** [comment]
I'm going with this one.

**Comment by mtojek** [comment]
Suggested command:

```
elastic-package service up
elastic-package service down
```
