### ISSUE TITLE
Fix issues with terraform in aws_logs test package

### ISSUE THREAD

**Issue by jsoriano** [elastic/elastic-package#1950]
It looks like we hit some limit of buckets with the `aws_logs` test package and it frequently fails. Find a solution for it.

Skipping failing tests in https://github.com/elastic/elastic-package/pull/1951.

**Comment by mrodm** [comment]
> It looks like we hit some limit of buckets with the `aws_logs` test package and it frequently fails. Find a solution for it.

Exactly, in the current AWS project used in the CI we're hitting a limit of the number of buckets, and testing packages using terraform (with AWS) are failing when trying to create buckets (most of the packages create buckets for testing purposes). Usually the error is like this one:
```
 Error: creating S3 Bucket (elastic-package-aws-bucket-35198): operation error S3: CreateBucket, https response error StatusCode: 400, RequestID: ..., HostID: ..., api error TooManyBuckets: You have attempted to create more buckets than allowed
```
