### ISSUE TITLE
[docs] add link to clean elastic-package usage docs

### ISSUE THREAD

**Issue by nicpenning** [elastic/elastic-package#1974]
As a user of Elastic Package, I enjoy using this guide: https://www.elastic.co/guide/en/integrations-developer/current/elastic-package.html

This is referenced in the Elastic Integrations repo nicely.

Would there be any issues with referencing in the main Readme.md for this repo like this is? https://github.com/elastic/integrations/blob/main/CONTRIBUTING.md

I find myself going to that documentation as it is a but more user friendly. This could help others get jump started with building integrations and not be confused with the development of elastic-package itself.

Thoughts?

**Comment by jsoriano** [comment]
Hey @nicpenning, nice suggestion, and happy to see you find the developers guide useful!
Feel free to open a PR with your suggestion, and we can discuss there.
Thanks!

**Comment by nicpenning** [comment]
Sounds good,  I will give it go!

**Comment by nicpenning** [comment]
QQ, what's the process for updating this project's readme? When I go to edit it says it is a generated file. 🤔
