### ISSUE TITLE
elastic-package check does not format

### ISSUE THREAD

**Issue by ltflb-bgdi** [elastic/elastic-package#2024]
Console output of `elastic-package check` does not show the formatting step.

A quick test of adding some extra lines to the end of a fields.yml file shows that the lines are not removed by `elastic-package check`, but only after running `elastic-package format`. 

A quick look at the code shows this: https://github.com/elastic/elastic-package/blob/1412f01ca7895ee47681dc250a4d7acdd49da0ea/cmd/check.go#L26

Should contain setupFormatCommand() as well IMO.

**Comment by jsoriano** [comment]
Hey @ltflb-bgdi,

Formatting was intentionally removed from check in https://github.com/elastic/elastic-package/pull/1936.

We consider that validation commands should not modify the working copy, specially given that there is another command that can help with formatting.

**Comment by ltflb-bgdi** [comment]
@jsoriano Thanks for clarification. But then it would help to remove it from the docs as well!

**Comment by jsoriano** [comment]
> @jsoriano Thanks for clarification. But then it would help to remove it from the docs as well!

Good point, updating docs in https://github.com/elastic/elastic-package/pull/2028.
