### ISSUE TITLE
[System test runner] Support for multiple tests per data stream

### ISSUE THREAD

**Issue by andrewkroh** [elastic/elastic-package#208]
Data streams can have multiple input options such as logfile, syslog over UDP, and syslog over TCP. In order to have test coverage over all of the supported input configurations we need a way to execute more than one system test per data stream.

Current a single test is declared in `data_stream/<name>/_dev/test/system/config.yml`. If we can expand this to allow more than one test definition then we'll be able to expand test coverage.

- Relates: https://github.com/elastic/integrations/issues/377

**Comment by ruflin** [comment]
@andrewkroh Does each of these have a separate stream template?

**Comment by andrewkroh** [comment]
Yes, as an example this package has a template for the UDP input and a logfile input. https://github.com/elastic/integrations/tree/0d55adaa4ea33e94b05f5c5106cc22c845b720ae/packages/checkpoint/data_stream/firewall/agent/stream

**Comment by ruflin** [comment]
👍 Each template should allow its own test. I'm wondering if we should go so far to allow each template multiple tests?

**Comment by andrewkroh** [comment]
Implemented in https://github.com/elastic/elastic-package/pull/209.
