### ISSUE TITLE
Command: publish

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-package#21]
Since `elastic-package` aims to be the primary tool for Integrations package authors, I propose we add a new sub-command to it: `publish`. This command would be in the same vein as [`npm publish`](http://doc.codingdict.com/npm-ref/cli/publish.html), [`gem push`](https://guides.rubygems.org/command-reference/#gem-push), and their ilk. Its usage would be as follows.

```
$ elastic-package publish [registry stage] [--dry-run]
```

Where:
* `registry stage` could be one of `snapshot`, `staging`, or `production`; the default would be `snapshot`.
* `--dry-run` would show the steps that would be taken without actually taking them.

The command would build the package and make a PR to the appropriate branch of the `package-storage` repository. In the future, if/when the package registry service offers an HTTP API to publish packages, the implementation could be updated to use this API instead of making the PR.

**Comment by mtojek** [comment]
As @ycombinator suggested in https://github.com/elastic/elastic-package/issues/153 , let's use this command as a replacement for updating the package storage. The command will be called by the CI.

**Comment by ycombinator** [comment]
Now that we have structured package changelogs, maybe we could use  `elastic-package publish` (the command described by this issue) to automatically update them? I'm not sure exactly what that process would look like but just wanted to capture the idea here for now.

**Comment by mtojek** [comment]
I'd like to start the implementation in terms of https://github.com/elastic/integrations/issues/730 . I will try to make as clear as possible, but keep in mind that this command will be executed by the CI too.
