### ISSUE TITLE
[Test Coverage] Multiline YAML strings not accounted for in pipelines

### ISSUE THREAD

**Issue by andrewkroh** [elastic/elastic-package#2111]
When pipeline YAML source lines are associated to a specific processor, our code does not account for YAML blocks that may span multiple lines. In this case, a `script` processor that uses a multiline `source` shows only the line containing the `source:` as covered but not the entire value.

![Image](https://github.com/user-attachments/assets/ccc61a1d-47f1-4cba-b3ca-e73e9d83b4d8)

![Image](https://github.com/user-attachments/assets/cede865c-40d9-4bbd-b5d5-b38a2df6d8cb)

References

- https://github.com/elastic/integrations/pull/11115#issuecomment-2361460645

**Comment by jsoriano** [comment]
@haetamoudi is working on this issue in https://github.com/elastic/elastic-package/pull/2063
