### ISSUE TITLE
[system tests] Validate fields are documented via the mappings generated after ingesting docs comparing them to the preview mappings

### ISSUE THREAD

**Issue by mrodm** [elastic/elastic-package#2206]
In order to try to be agnostic to the structure of the documents ingested to run the validation in system tests. It would be helpful to run validations comparing the mapping definitions instead.

These validations should be done with these two sets of mappings:
- Mappings and dynamic templates installed by Fleet before ingesting any doc.
    - These preview mappings can be retrieved using this simulated API:
      ```
      POST /_index_template/_simulate/<index_template_name>

      # Example
      POST /_index_template/_simulate/logs-microsoft_dhcp.log
      ```     
- Mappings and dynamic templates that are present after ingesting the docs as part of the system tests.
    - These mappings can be retrieved using this API:
      ```
      GET /<data_stream_test>/_mapping/
      ```

Being available these two sets of mappings, it would be needed to validate whether or not each mapping present in the data stream (after ingesting docs) has a corresponding mapping in the preview.

It should be taken into account that:
- Some fields should be skipped (e.g. `agent.*`, `host.*`, ...) as it is done nowadays ([link](https://github.com/elastic/elastic-package/blob/e6aa8c4762c55918f649aaf230f12c24ff536842/internal/fields/validate.go#L818))
- Ignore for now those mappings that are not found in the preview (to be done in the next step).
    - To be done in a follow-up issue.
- TBD check if any mapping that does not exist in the preview is part of the ECS.

For now, the errors that could be raised as part of this validation should not make fail the validation process, therefore:
- Ignore at this step mappings not found in the preview, to be done in the next step.
- Enable via environment variable this mapping or show just just warning messages.

To be tested:
- Run these validations in stack 7.x
- Run these validations in stack 8.x
- Run these validations in input and integration packages.
- Run these validations in Stacks with LogsDB enabled (synthetics).

**Comment by mrodm** [comment]
🚧  (WIP) 
Some assumptions made when adding this new validation based on mappings:

- Objects with type `array` are skipped.
    - Type `array` is checked using the local field definitions in the package.
        - Requires to load in memory also the field definitions from the data stream or input package.
    - These kind of definitions were allowed in spec versions <= 2.0.0 ([link](https://github.com/elastic/elastic-package/blob/main/docs/howto/update_major_package_spec.md#field-type-type-must-be-one-of-the-following))
- Empty objects present in the actual mappings are skipped:
  ```json
  "_tmp": {
    "type": "object"  
  }
  ```
- If a field is defined as a `constant_keyword`, just check/validate the value if both (preview and actual mappings) have "value" parameter.
- If an object contains `dynamic: true`:
    - skip the validation of those field mappings under a mapping like
        - should they be validated using the dynamic template definitions?
      ```json
        "field": {
          "dynamic": true,
          "type": "object"
        }
      ``` 
    - The other field mappings must be checked as regular field mappings.

**Comment by mrodm** [comment]
While working on https://github.com/elastic/elastic-package/pull/2214 , there have been some issues found while testing with the packages in the integration repository that are not related to the dynamic templates. Support to validate mappings with the dynamic templates is going to be tackle in https://github.com/elastic/elastic-package/issues/2207

Issues found are detailed in https://github.com/elastic/elastic-package/pull/2214#issuecomment-2493604300

In summary, those issues are:
- Failures related to different mappings found in ECS
   - Due to the embedded ECS or the `ecs@mappings` component template
   - Some examples:
       - https://github.com/elastic/elastic-package/pull/2214#issuecomment-2493988706
       - https://github.com/elastic/elastic-package/pull/2214#issuecomment-2493949822
- Failures while validating mappings with type long, float or double https://github.com/elastic/elastic-package/pull/2214#issuecomment-2494105617
- Nested objects https://github.com/elastic/elastic-package/pull/2214#issuecomment-2493731704
   - Skip for spec versions <3.0.1
- Array of objects defined as `group` in the package https://github.com/elastic/elastic-package/pull/2214#issuecomment-2497425485

**Comment by mrodm** [comment]
With the latest changes introduced in the PR, the missing failures are related to different mappings found in ECS. That could probably be checked as part of the following issue where dynamic templates are going to be considered https://github.com/elastic/elastic-package/issues/2207

WDYT @jsoriano ? 

Nested and groups field/mappings should be fixed , testing it in https://github.com/elastic/integrations/pull/11828 (build https://buildkite.com/elastic/integrations/builds/19362).


Found an unexpected error for `tines` package, described in https://github.com/elastic/elastic-package/pull/2214#issuecomment-2536692641

**Comment by jsoriano** [comment]
> With the latest changes introduced in the PR, the missing failures are related to different mappings found in ECS. That could probably be checked as part of the following issue where dynamic templates are going to be considered [#2207](https://github.com/elastic/elastic-package/issues/2207)

Yes, I think we can go on with current implementation and polish it in follow ups.

> Found an unexpected error for `tines` package, described in [#2214 (comment)](https://github.com/elastic/elastic-package/pull/2214#issuecomment-2536692641)

This looks like an issue in Fleet (see https://github.com/elastic/elastic-package/pull/2214#issuecomment-2536939715), I will take a deeper look tomorrow.
