### ISSUE TITLE
Support `traces` data stream type

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-package#223]
In https://github.com/elastic/package-spec/pull/78, a new data stream type, `traces`, was added for supporting APM packages. This may have implications on `elastic-package`. We should figure out what those might be and support this new type.

cc: @elastic/apm-server.

**Comment by mtojek** [comment]
I guess we can close this issue, @ycombinator ?

**Comment by ycombinator** [comment]
I'm not sure. Do we do anything special for `logs` vs. `metrics` in `elastic-package`? IIRC there's a conditional in the code for pipeline tests so they only run on `logs` data streams? I was hoping to look for such special cases and see if we need to account for `traces`. I'm 90% sure we are good as-is, but just wanted to look through the code and make sure of it.
