### ISSUE TITLE
test asset: validate fields in sample event

### ISSUE THREAD

**Issue by mtojek** [elastic/elastic-package#226]
The elastic-package should validate if sample events (JSON files) contain fields defined in the `fields` folder. I spotted in the Integrations repository, that some files don't only contain events, but also wrapping fields with underscores:

```
{
    "_index": "metrics-aws.sns-default-000001",
    "_id": "Ds9vXHIBpGMSUzkZmyod",
    "_version": 1,
    "_score": null,
    "_source": {
        "@timestamp": "2020-05-28T17:58:27.154Z",
        "service": {
            "type": "aws"
        },
        "stream": {
            "dataset": "aws.sns",
            "namespace": "default",
            "type": "metrics"
        },
        "ecs": {
            "version": "1.5.0"
        },
```

For reference:
https://github.com/elastic/integrations/blob/master/packages/aws/data_stream/sns/sample_event.json#L6

**Comment by ycombinator** [comment]
Just to clarify: this issue is about making sure that we don't end up with underscore-delimited fields like `_source`, etc. in `sample-event.json` files, correct?

**Comment by mtojek** [comment]
Yes, most likely it will result also in adjustments in current integrations.

**Comment by mtojek** [comment]
Based on the comment https://github.com/elastic/elastic-package/pull/251#issuecomment-781361651 , I will create a new test runner, let's say - `static`, which can be used to check static resources, which are not installed in Kibana (they're just static).

**Comment by mtojek** [comment]
There is another constraint (just discovered). All "per data stream" test runners require to have a corresponding `_/dev/test/<test_type>` available. I wouldn't like to hardcode a hack for Static Test Runner not to require such directory, so I'll try to introduce a similar mechanism like `CanRunPerDataStream`, e.g `TestFolderRequired`.

**Comment by ycombinator** [comment]
You mean like this: https://github.com/elastic/elastic-package/pull/168#discussion_r525055005? 😉

**Comment by mtojek** [comment]
A kind of :) I started with a bit different implementation, we can discuss it on code review.
