### ISSUE TITLE
[Fleet] /api/fleet/setup fails with HTTP 500

### ISSUE THREAD

**Issue by mtojek** [elastic/elastic-package#234]
Hi,

while executing Integration Tests in package-storage (https://github.com/elastic/package-storage/pull/824#issuecomment-768872833), we spotted a problem with Kibana and Elasticsearch. Kibana failed with HTTP 500 due to `unavailable_shards_exception` for `.security` shard.

The goal of this issue is to research if there is a possibility to find a mitigation for this.

Logs available at: https://github.com/elastic/package-storage/pull/824#issuecomment-768872833

**Comment by ph** [comment]
Just to make sure the loop is complete.

By default ES will uses indices to store the credentials, the shard needs to go green before it's available. This means that if the host machine is over capacity it can take a while for it to go green. When I was hit by this issue, I was not able to reproduce it easily. Adding timeout or weirds check never really fixed the problem.

If you look at Elasticsearch integration testing they are all using the file ream as the backend for credentials and by using them it won't need to replicate the shard and the test will be stable and fast.

This is the strategy we have used in https://github.com/elastic/beats/blob/master/x-pack/libbeat/docker-compose.yml

**Comment by jsoriano** [comment]
Please reopen if still an issue.
