### ISSUE TITLE
Terraform deployer: implement env-file

### ISSUE THREAD

**Issue by mtojek** [elastic/elastic-package#235]
Issue: https://github.com/elastic/elastic-package/pull/227#discussion_r565746042 https://github.com/elastic/elastic-package/pull/227#discussion_r565754848

> It would be really nice if we could keep any mention of integration-specific variables/constants out of the elastic-package source code. I know there is another place where this is happening as well. Similar to the other place, could you please add a TODO comment here with a link to an issue for cleaning this up?

The goal is to extract all cloud provider specific environment variables from the Docker image and just pass an env file with related ones.

**Comment by mtojek** [comment]
@ycombinator Actually we need to design a clean way of passing these environment variables. It would mean that we'll have to load them in Docker runtime (not in service compose definition) and most likely we've to add a `env-file` with variable names in the "terraform" directory.

**Comment by mtojek** [comment]
I'm going with this.

**Comment by mtojek** [comment]
I research different methods in terms of user experience and security.

Method 1.

I started with a basic `env` file, which contains a list of global variables, that should be passed to the Terraform Docker application. `env` file's content:

```
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
AWS_SESSION_TOKEN
```

The file is processed by the system test runner and used to create a local `_dev/deploy/tf/env-file`:

```
AWS_ACCESS_KEY_ID="1111"
AWS_SECRET_ACCESS_KEY="2222"
AWS_SESSION_TOKEN="3333"
```

Unfortunately this file must be stored in the file system (`~/.elastic-package/tmp/env-file`) and is replaced every time per data stream's system test. It's a security threat as we're storing credentials in some local file and if the elastic-package doesn't exit correctly (process interrupted or crashed), the file is a left-over.

Method 2.

In the `_dev/deploy/tf` directory we add a new `.yml` file, e.g. `aws.yml`:

```yaml
version: '2.3'
services:
  terraform:
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_PROFILE=${AWS_PROFILE}
      - AWS_REGION=${AWS_REGION:-us-east-1}
```

This file is an extension to the Terraform docker compose definition, it allows for definition global variables that should be loaded into Docker service without storing secrets anywhere in the filesystem. The system tests runner loads this file (`services.terraform.environment)` to lookup for environment variables to replace placeholders in the `test-system-config.yml`.


Results:

Due to security concerns I prefer to go with the Method 2. There is a drawback of this solution - we need to copy the `aws.yml` file to every `tf/` directory. On the other hand it allows for configuring different environment variables (regions, session tokens, partitions, etc.).

**Comment by ycombinator** [comment]
++ to Method 2. I'm a little fuzzy on the actual implementation details but that should become clearer once I see the PR for this solution. Thanks!
