### ISSUE TITLE
Command: version

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-package#24]
The command would output the version of `elastic-package` currently installed. 

As `elastic-package` is rapidly under development it would be good to know which version is being run for debugging issues from users, etc.

**Comment by exekias** [comment]
This would be nice, I'm wondering what will be the release cycle here? It sounds like for now we may want to stay up to date will any change to master? In that case the version would be the commit hash 😈 

I created this related issue: https://github.com/elastic/elastic-package/issues/32
