### ISSUE TITLE
Compiling packages with elastic-package build

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-package#259]
_I'm not sure if this is the best repo for this conversation but it felt like the closest one. If it turns out there's a more appropriate repo after discussion, we can move this issue there._

Today, when a user runs `elastic-package build`, we do a few things to the _source_ contents of the package in order to generate a _built_ version of that package:

- it generates a [`docs/README.md`](https://github.com/elastic/package-storage/blob/production/packages/apache/0.3.3/docs/README.md) file from the [`_dev/build/docs/README.md`](https://github.com/elastic/integrations/blob/master/packages/apache/_dev/build/docs/README.md) file.
- it extracts the version number from the package manifest and creates a version folder to hold that package version's contents.
- it excludes any `**/_dev` folders from the "compiled" package contents since those are meant to contain development-time-only files, e.g. test files.

There is a [suggestion](https://github.com/elastic/integrations/issues/729#issuecomment-783435670) that we could add another step to the ones listed above, to minify JS assets contained within a package's source.

More generally, it might be good to start thinking of packages as having a **source** flavor and a **compiled** or **built** flavor. Some ideas and questions around source vs. compiled packages:
- Repositories like https://github.com/elastic/integrations would contain source packages while packages that have been released to the package registry (so packages that live in the https://github.com/elastic/package-storage repository) would contain compiled packages, maybe with the exception of the `snapshot` branch as some developers/teams use it as a development area?
- A source package may be modified freely but once a compiled package enters the package registry, it is immutable (again, with the possible exception of the `snapshot` branch). Any changes must be released as a new version.
- The [package specification](https://github.com/elastic/package-spec) applies to source packages, as it stands today anyway. Do we want a separate/parallel spec for compiled packages so we could use it for validation in the https://github.com/elastic/package-storage repository and later in the Fleet UI in Kibana?
- Besides the compilation steps listed above, what other steps might make sense to include as part of `elastic-package build`?

**Comment by ycombinator** [comment]
cc: @mtojek @andrewkroh @ruflin as folks I've had this discussion with in 1-1 conversations. Please feel free to tag more people who might be interested/affected and should participate in this discussion.

**Comment by mtojek** [comment]
> There is a suggestion that we could add another step to the ones listed above, to minify JS assets contained within a package's source.

Let me challenge it: what is the exact issue we are trying to solve? Is the pipeline file just too big or loading it takes too much or is it just slow execution?
Keep in mind that Kibana downloads the gzipped package from package registry, there is no gain in additional gzipping unless Kibana handles smaller files better.

This will also make debugging issue much harder (standard problem with minified scripts - error in line no 1).

**Comment by ycombinator** [comment]
@mtojek The minification suggestion was based on @andrewstucki's analysis in https://github.com/elastic/integrations/issues/729#issuecomment-782562380. That issue is specifically about minification so let's take that specific conversation there? This issue here is more for discussing the general idea of going from source packages to compiled packages via `elastic-package build` (and minification could be a part of this compilation or not).

**Comment by ruflin** [comment]
++ on the general idea. Having a build step will allow us to improve the development experience but at the same time keep a simple structure on the package side without references / dependencies etc.

Even if we have a build step, it should still be possible for a user to build a simple package directly. What I mean by that after the build step their might be repeated / optimised files but they should not be in a format which is not possible for a dev to create.
