### ISSUE TITLE
[Discuss] Limit package data stream fields

### ISSUE THREAD

**Issue by jen-huang** [elastic/elastic-package#266]
Spinning off the discussion from https://github.com/elastic/kibana/pull/91791. For every data stream index template we install, that Kibana PR adds all keyword/text fields `index.query.default_field` setting. In an edge case scenario, a package may export a very large amount of keyword/text fields that exceeds the setting limit (1024 fields by default). That PR has a safeguard to prevent such cases, but led to a discussion around how we can help package authors detect when they may have too many fields defined.

Could we help them via `elastic-package` tooling and/or package spec changes?

cc @ycombinator @ruflin 

---

_Originally posted by @ycombinator in https://github.com/elastic/kibana/issues/91791#issuecomment-785384137_

> To get started, I would add a general field limit in packages per data_stream. In general, the number of fields per data_stream should stay low to have compact mappings. I'm thinking of starting with something like 128 or 256 and increase it only if we see good reasons for it. This will encourage package devs to think about which fields are added.

If we do this, wouldn't package developers just keep bumping up the limits until the validation passes? Or maybe this is actually desired to give them the escape hatch that @andrewkroh mentioned?

By the way, where were you thinking of having validation against this new limit field be implemented?

I was thinking it could be implemented as part of `elastic-package lint` or maybe `elastic-package test` even, depending on whether we can simply analyze a data stream's field definition files (`fields.yml`, etc.) or we need to install the package so it's data streams' index templates also get installed and then analyze the fields in the template's mapping. Of course, as @andrewkroh also pointed out, any packages that don't use `elastic-package` would escape such validation then.

If we are okay with implementation the validation as part of `elastic-package lint` or `elastic-package test`, then maybe we could also consider _hardcoding_ a limit in `elastic-package` code rather than giving package developers the ability to set the limit per data stream? That would ensure that when package developers start to hit the limit, they don't silently bump it up but have to file an issue against `elastic-package`, which then gives us an opportunity to figure out _why_ they need the higher limit and maybe suggest some alternatives. Again, any packages that don't use `elastic-package` would escape this validation.

**Comment by ycombinator** [comment]
@mtojek It would be good to get your thoughts on this discussion.

**Comment by mtojek** [comment]
>Again, any packages that don't use elastic-package would escape this validation.

Unfortunately we know such customers. Speaking about others, what do you think about setting the hard limit to 256 in spec and wait for people's feedback? If we believe that 256 is enough, we should consider it as hard limit (without any discussions). If it's insufficient, we can raise it globally to 512.

**Comment by ycombinator** [comment]
> Speaking about others, what do you think about setting the hard limit to 256 in spec and wait for people's feedback? If we believe that 256 is enough, we should consider it as hard limit (without any discussions). If it's insufficient, we can raise it globally to 512.

I think the part I'm missing is what it means to set a limit in the spec.

If it means introducing a new field somewhere in the data stream manifest with a default value of 256, then any package developer could easily override this field's value to bypass the check, no?

Alternatively, I was thinking we set (hardcode) it in `elastic-package` source code OR even the `package-spec` Golang validation code. If we get feedback about it being too low we can try to figure out why that particular data stream needs a higher limit and, if it's a valid use case, bump up the hardcoded value.

**Comment by ycombinator** [comment]
> I thought we can use the format checker to verify it.

Would a package author be able to override the value by changing a field in one of their manifest files? That's really my only concern. 🙂

**Comment by mtojek** [comment]
It all depends on the implementation, I would say the easier path would be to prohibit custom changes: https://github.com/elastic/package-spec/blob/master/code/go/internal/validator/folder_item_spec_format.go

**Comment by ycombinator** [comment]
Okay, then I think we are on the same page. This is what I meant by:

> I was thinking we set (hardcode) it in ... the `package-spec` Golang validation code.

**Comment by jsoriano** [comment]
It is already possible to define a limit of fields per data stream. It is currently set to 2048 https://github.com/elastic/package-spec/blob/5cf4f70023e5f69d741202cda3a9b6dd5cadbd41/spec/integration/spec.yml#L13C1-L13C33
