### ISSUE TITLE
Elastic stack: support Fleet Server 

### ISSUE THREAD

**Issue by mtojek** [elastic/elastic-package#278]
The goal of this issue is to ensure that the Fleet Server is enabled for the Elastic stack setup.

Known differences / to be solved:
- [x] new policy for the fleet server (should be supported by test runners)
- [x] Blocker: https://github.com/elastic/beats/issues/24447 https://github.com/elastic/beats/pull/24631 (backport)
~- [ ] Blocker: https://github.com/elastic/beats/issues/24467~ (most likely not a blocker anymore, but no-go for support of 7.12 and 7.11, environment variables are in conflict between versions)
- [x] Blocker: https://github.com/elastic/beats/issues/24453 (can't observe anymore)
- [x] Blocker: https://github.com/elastic/kibana/issues/95179
- [x] Blocker: https://github.com/elastic/beats/issues/24725 https://github.com/elastic/fleet-server/issues/176 https://github.com/elastic/fleet-server/pull/183
- [x] Blocker: https://github.com/elastic/beats/issues/24503 https://github.com/elastic/beats/pull/24856 https://github.com/elastic/beats/pull/24905
- [ ] Blocker: https://github.com/elastic/kibana/issues/95896 (related? https://github.com/elastic/kibana/issues/95388)

Are older stacks working?
~- [ ] 7.12.0~ no: https://github.com/elastic/beats/issues/24467#issuecomment-800351116
~- [ ] 7.11.2~ no: https://github.com/elastic/beats/issues/24467#issuecomment-800351116

**Comment by ruflin** [comment]
Comment on the older stacks: 7.11 and 7.12 are not expected to work.

**Comment by mtojek** [comment]
It depends on the set of environment variables. Maybe it's possible to select such set that all stacks work correctly. Even though I agree to give priority to the latest (7.13).

**Comment by mtojek** [comment]
Status update:

With support of @nchaulet , I managed to start the agent, connect to the fleet server and enroll. I suppose we eliminated this way one blocker. Unfortunately it seems that we can't comprise a complete list of environment vars that will be suitable for 7.13, 7.12, 7.11 as vars are in conflict with each other (different behavior).

**Comment by mtojek** [comment]
Next status update:

Another issue spotted. Either the agent can't pick up the policy or it doesn't confirm that it was picked - https://github.com/elastic/kibana/issues/95179 .

**Comment by mtojek** [comment]
Status update:

It looks like we fixed all issues or at least they're not bumping up here.

**Comment by ruflin** [comment]
@mtojek Thanks a lot for pushing through all these. It caused a lot of work on your end but helped the other teams to make the product better ❤️
