### ISSUE TITLE
CI: Setup Hound

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-package#28]
Similar to the Beats repo, I think we should setup [Hound](https://houndci.com/) to catch common golang linting errors and variances from suggested practices.

**Comment by mtojek** [comment]
Git hooks are just a mean of execution here. I'm not familiar with any offline alternative to Hound - just used to enable it in the past. We have also static checks enabled [here](https://github.com/elastic/elastic-package/blob/7fc8ed88435957c12e10b203ff4e4518bb6f57a0/Makefile#L16).

I don't have strong preference, to be honest I thought that this is a standard (comparing to Beats).

WDYT @jsoriano ?

**Comment by jsoriano** [comment]
> Without much context, what's the benefit of using an external service for linting rather than some other approach within the build system?

Hound automatically made a review in the PR in github, but at the end it is the same information as a linter but with a different UI.

I also think that ensuring that linters are run at least on PRs is good enough. And ensuring that the same thing can be run locally or in a pre-commit is a plus, this cannot be done with hound.
