### ISSUE TITLE
Flag and link ECS fields in generated README files

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-package#293]
See the conversation about the ECS flag starting from https://github.com/elastic/apm-server/issues/4973#issuecomment-803843898. We want to implement something similar for all packages in general. 

Concretely, when a user runs `elastic-package build` to regenerate README files, we want ECS fields in these generated README files to be flagged as ECS fields and linked to the ECS field reference. Bonus points for deep linking to the specific field's reference.

**Comment by mtojek** [comment]
This feature is already available since we introduced dependency management for external field sources (currently, ECS only).
