### ISSUE TITLE
Replace os.IsNotExist(err) usage

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-package#299]
Follow up to https://github.com/elastic/elastic-package/pull/292#discussion_r600696184.

According to https://golang.org/pkg/os/#IsNotExist, we should be using `errors.Is(err, os.ErrNotExist)` instead of `os.IsNotExist(err)`. This issue is to track replacing the old usage across the `elastic-package` codebase.

**Comment by anirudhramnath** [comment]
Hi, I am looking for my first contribution and would love to help on this.

**Comment by anirudhramnath** [comment]
@ycombinator Would you be able to provide some guidance on how to fix the failing checks in the PR? I have signed the agreement already.

**Comment by mtojek** [comment]
Well done, @kush-crest ! Thanks for workin on this.
