### ISSUE TITLE
Command: create new integration

### ISSUE THREAD

**Issue by mtojek** [elastic/elastic-package#3]
The command bootstraps the structure for a new integration using a wizard or command line arguments.

Suggested command: `elastic-package create`

Subcommands:

```
create package
create data-stream
```

**Comment by mtojek** [comment]
I'm going with this one. We need it to close the development workflow (the last missing piece).

**Comment by exekias** [comment]
This is great 🤟, do you have a list of the subcommands that you plan to add? I see `package` is in progress already, I guess others will come

**Comment by mtojek** [comment]
I updated the issue description for visibility. MVP includes "package" and "data-stream".

**Comment by exekias** [comment]
SGTM! Other obvious assets that most devs will hit are pipelines & dashboards, I think it's fine to add them later, happy to create issues to discuss them

**Comment by mtojek** [comment]
Yeah, we can research it later. Speaking of dashboards, there is the "export" command that helps you pull them from Kibana to local files.

**Comment by mtojek** [comment]
I'm going with the `create data-stream` command.

**Comment by mtojek** [comment]
Implementation has been merged, I'll write HOWTO doc page describing the procedure.
