### ISSUE TITLE
Proposal: Limit promote command to one package

### ISSUE THREAD

**Issue by ruflin** [elastic/elastic-package#305]
Currently with `elastic-package promote` it is possible to promote multiple packages. This was needed in the past where we bulk promoted packages. But we should switch over to a mode where each package developer / owner makes sure their packages are promote and tested. Because of this I propose that promote has to be run for a specific package and make it default to have it run for each package.

I can foresee cases where the bulk might still become useful in the future. Perhaps we can add a flag `--all` to the promote command to keep this functionality if we need it.

**Comment by ycombinator** [comment]
I like this idea. To put it differently, in terms of `elastic-package` terminology, `promote` currently has "global" scope; now we would want it to be "package" scope.

One way we could achieve this is by checking if we are in a package context or not. Being in a package context means that the user is somewhere inside a package folder's hierarchy.

@ruflin Just curious: what is the use case driving this change?

**Comment by ruflin** [comment]
This was triggered by PR's like these: https://github.com/elastic/package-storage/pull/1079 https://github.com/elastic/package-storage/pull/1078 The is impossible to tell from the title if one or many packages were changed. Also I'm worried that potentially packages are "accidentially" promote if it is not done one by one. Last, it is also about ownership to make sure everyone handles their packages. If we have a proper package publish API one day, I doubt bulk would exist.

**Comment by ycombinator** [comment]
Thanks @ruflin. Interestingly @mtojek recently created [`elastic-package publish`](https://github.com/elastic/elastic-package/pull/292) which does the initial publishing of a package to the `snapshot` branch... and this command runs in a ["package" context](https://github.com/elastic/elastic-package#elastic-package-publish)! So I'm even more ++ to aligning `elastic-package promote` to also require "package" context.

@mtojek WDYT?

**Comment by mtojek** [comment]
I can give more context for the bulk option - in the early days it was common to adjust multiples packages at once when we're introducing new fields or modifying the structure. This option is also used to promote packages parked in staging after the testing phase.

I'm ok with overall idea, but we need to focus on the CLI/UX. Keep in mind that `elastic-promote` doesn't operate on packages in Integrations, but built ones in package-storage (not all packages are in the integrations repo). I'm looking for CLI proposals :)

**Comment by ruflin** [comment]
My CLI proposal would be:

```
elastic-package promote {package-name+version} {target}
```

An example here would be:

```
elastic-package promote apache-1.3.2 staging
```

This would not have to be run in any specific location. If `apache-1.3.2` does not exist in snapshot, the command will fail. This will ensure packages go through all stages.

**Comment by mtojek** [comment]
@andrewkroh @jonathan-buttner 

Any comments on this modification?

**Comment by ycombinator** [comment]
>  Keep in mind that `elastic-promote` doesn't operate on packages in Integrations, but built ones in package-storage

Ah yes, thanks for reminding me of this. In that case the command will stay in the "global" context.

I'm good with @ruflin's proposal of:

```
elastic-package promote apache-1.3.2 staging
```

One question using the above example: let's say `apache-1.3.2` exists in `production`. Would we still allow it to be "promoted" to `staging` in that case? It would actually be a demotion so I think we'd want to guard against packages being able to "backwards" or "downwards" through the registry stages?

**Comment by andrewkroh** [comment]
> This option is also used to promote packages parked in staging after the testing phase.

This is something I've done - promote to staging, do some hands on testing, and then promote several to production at once. 

> I can foresee cases where the bulk might still become useful in the future. Perhaps we can add a flag --all to the promote command to keep this functionality if we need it.

Unless this bulk promote is some kind of anti-pattern then I'd like to keep that as an option. I wouldn't care if it opened multiple pull requests to satisfy the concern that it "is impossible to tell from the title if one or many packages were changed".

**Comment by ruflin** [comment]
My main concern is that "accidentally" some packages from an other dev are promoted. Same for the different versions, it might be that 2 versions of the same package are on staging, which one should be promoted. I personally think of "promote everything" as an anti pattern but not "promote these packages". 

@andrewkroh Would the following (or similar) be sufficient for your use case:

```
elastic-package promote  staging --packages=[apache-1.3.2,nginx-2.1.3,foo-1.1.1]
```

**Comment by jonathan-buttner** [comment]
@mtojek thanks for the ping. The endpoint team doesn't use the functionality to promote multiple packages at once so I think we're ok on that front. How do we feel about keeping the functionality to promote from snapshot directly to production 😬  Endpoint does their testing in snapshot and the package-storage PRs take ~20 minutes to build so not having to go through staging speeds up our release process 😄 

cc: @kevinlog @pzl

**Comment by ruflin** [comment]
@jonathan-buttner I'm ok to keep it if it is not our default behaviour. Something like 

```
elastic-package promote  -from=snapshot --to=production --packages=endpoint-1.2.3
```

I'm pretty sure all the params I made up in my recent posts do not work in combination but I hope it provides an idea.

**Comment by ruflin** [comment]
I would like to see this moving forward. The reason is that I think this will increase the developer experience. I just promoted a package and all the PR's are named the "same". It it not possible based on the title to figure out what was promoted and what was removed.

**Comment by ruflin** [comment]
A bit a more visual representation of the problem 😆 

![Screenshot 2021-05-19 at 08 39 34](https://user-images.githubusercontent.com/244900/118767302-d641ee80-b87d-11eb-9968-75eece8e0568.png)

**Comment by mtojek** [comment]
I will try to look into this in the next week (I'm on the SDH duty this week) and we have limited capacity.
