### ISSUE TITLE
Proposal: Pending package changes/status

### ISSUE THREAD

**Issue by andrewstucki** [elastic/elastic-package#313]
It would be nice to have a command that allows us to see at a glance the status of a package -- what versions are released in which environments, and which changes are still "pending" (i.e. are in the changelog/code, but have not yet been built/released by a manifest version update and PR to package-storage snapshot).

One thing that has happened in the past is that a change in one of the packages our team is responsible for got pushed to our snapshot branch, but never promoted fully to production until someone was wondering why they didn't see a package when they were wanting to try something out a week or so after we thought we had released the change. A command showing a package status would make these easier to surface.

**Comment by ruflin** [comment]
++ on this idea. @andrewstucki Would your team be interested to contribute this?

**Comment by andrewstucki** [comment]
I personally wouldn't mind, unless someone else wants to do the implementation or pick it up sooner. If I get some free cycles in the next couple of weeks I can try to pick it up.

**Comment by ruflin** [comment]
Would be great, thanks!
