### ISSUE TITLE
Use upstream's manifest to deploy agent on k8s for tests

### ISSUE THREAD

**Issue by ChrsMark** [elastic/elastic-package#328]
Using upstream's manifests to deploy Agent on k8s for testing will keep testing process up to date with the proposed way of deploying agent on k8s. We will avoid hitting issues like https://github.com/elastic/elastic-package/pull/326.

Manifests: https://github.com/elastic/beats/blob/master/deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml

Note: The above manifests are for standalone version so version for far so we need a way to use them with managed version too for testing.

**Comment by MichaelKatsoulis** [comment]
After merging of https://github.com/elastic/beats/pull/26756 we have proposed manifests for fleet managed agent.
It would be nice for testing with elastic package to support multi node kubernetes cluster (maybe have it as default kind config [link](https://kind.sigs.k8s.io/docs/user/quick-start/#multinode-clusters)) and deploy agent as Daemonset . This approach resembles more to real world scenarios and helps test PRs like https://github.com/elastic/integrations/pull/1321

**Comment by mtojek** [comment]
👍 

But we need to make sure that all required ENVs are present. See: https://github.com/elastic/elastic-package/blob/master/internal/install/static_kubernetes_elastic_agent_yml.go#L39
