### ISSUE TITLE
format, lint: fail fast, but don't modify integration source

### ISSUE THREAD

**Issue by mtojek** [elastic/elastic-package#33]
The goal of this issue is to modify commands (format, lint) to fail fast when a specific flag is passed (e.g. `--fail-on-modification`). "Check" command will set and pass this flag to subcommands to fail in case of any inconsistency in the integration (e.g. not formatted source code).

**Comment by mtojek** [comment]
@ycombinator I assume that `lint` doesn't need this flag at all? This is mainly to prevent formatting on the CI side?

**Comment by ycombinator** [comment]
My understanding of this flag is something like this: "if modifications are detected, fail immediately". If so, then I agree — it doesn't make sense for `lint` to accept this flag.
