### ISSUE TITLE
go get is failing

### ISSUE THREAD

**Issue by masci** [elastic/elastic-package#342]
```
$ go version
go version go1.16.2 darwin/amd64
```

Steps to reproduce:
```
$ go get github.com/elastic/elastic-package
go get: github.com/elastic/elastic-package@none updating to
	github.com/elastic/elastic-package@v0.0.0-20210428124655-e522554fc3f2 requires
	helm.sh/helm/v3@v3.5.4 requires
	github.com/deislabs/oras@v0.10.0 requires
	github.com/docker/distribution@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

Problem seems to be upstream https://github.com/helm/helm/pull/9492

**Comment by ycombinator** [comment]
PR to resolve this issue in the short term: #343 
Issue to track long term upstream fix: https://github.com/elastic/elastic-package/issues/344

**Comment by ycombinator** [comment]
Looks like https://github.com/elastic/elastic-package/pull/345 didn't fix this issue either. 😞 Reopening...

**Comment by mtojek** [comment]
The original issue seems to be fixed: https://github.com/elastic/elastic-package/issues/344#issuecomment-829961027

@masci would you mind verifying it on your side?

Anyway, I'd like to keep this issue open as it proofed that we don't test code building procedure just with "go get". We need to figure out a bulletproof method.

**Comment by masci** [comment]
Works for me now:
```
~ go get github.com/elastic/elastic-package                                      
go: downloading github.com/elastic/elastic-package v0.0.0-20210430085756-cb436d9f36d9
<snip>
~ elastic-package version
elastic-package has been installed.
elastic-package version-hash undefined (build time: unknown)
```
Thanks!
