### ISSUE TITLE
Adjust wording to "package" rathen than "integration"

### ISSUE THREAD

**Issue by mtojek** [elastic/elastic-package#35]
The tool should be oriented on package development, not only integrations. @masci suggested to adjust all references to integrations and replaces with packages (where possible).

**Comment by ycombinator** [comment]
IIRC the original intent was for this tool to be just for integrations packages. Just want to clarify that going forward we want it to be used for _any_ packages (e.g. endpoint as well), yes?

**Comment by mtojek** [comment]
I understand this :

The tool is intended to be used for development of different packages, but currently we support "integrations" only.

**Comment by ycombinator** [comment]
Gotcha, limiting the scope that way for now sounds good. We should make sure none of the interfaces (commands, arguments to commands, etc.) are integrations specific so it's easy to grow the scope in the future. I think this is already the case but probably good to keep checking anytime we introduce a new interface that we're not backing ourselves into any corners that'd be hard to get out of later when we broaden the scope.

**Comment by masci** [comment]
Thanks for filing this issue!

@ycombinator  I think it's ok if the tool has a few integrations-specific subcommands (with relative flags and args) if needed, as integrations are indeed packaged. My intent was to consolidate the message we send through docs, source code and CLI about the scope of the tool, which might be (as @mtojek perfectly condensed in the comment above) _The tool is intended to be used for development of packages_.
