### ISSUE TITLE
Proposal: expand `status` to include status of the package-storage repo

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/elastic-package#362]
So, `elastic-package status` is really helpful, but the way releasing works, there's enough moving parts that ( in my experience) there's still room to get confused by what state everything is in, particularly considering how many moving pieces are in `package-storage`. It would be nice if we could expand `elastic-package list` to tell the user if the actual EPR endpoint is out of step with the `elastic-package` repo, or if the version in `integrations` doesn't exist in `package-storage` yet. In theory these "unsynchronized" states are temporary, but they've caused enough confusion during testing that it would be nice to see a blinking light somewhere, so to speak. 

Just one idea of how this could look:
```
+-------------+---------+--------------------------------+---------+--------+--------------------+
| ENVIRONMENT | VERSION |          REPO SYNCED           | RELEASE | TITLE  |    DESCRIPTION     |
+-------------+---------+--------------------------------+---------+--------+--------------------+
| Local       | 0.12.6  | elastic/integrations 0.12.7    | beta    | system | system Integration |
+-------------+---------+--------------------------------+---------+--------+--------------------+
| Snapshot    | 0.12.6  | Yes                            | beta    | system | system Integration |
+-------------+---------+--------------------------------+---------+--------+--------------------+
| Staging     | 0.12.6  | Yes                            | beta    | system | system Integration |
+-------------+---------+--------------------------------+---------+--------+--------------------+
| Production  | 0.10.6  | elastic/package-storage 0.12.6 | beta    | system | system Integration |
+-------------+---------+--------------------------------+---------+--------+--------------------+
```

**Comment by mtojek** [comment]
`elastic-package list` - did you mean the `status` command?

**Comment by fearful-symmetry** [comment]
Status, yah! Sorry about that.

**Comment by jsoriano** [comment]
Package storage is not used anymore, closing this.
