### ISSUE TITLE
Command: package version handling

### ISSUE THREAD

**Issue by masci** [elastic/elastic-package#37]
It would be handy to have a set of commands to deal with package versions. See for example https://github.com/elastic/integrations/pull/206 where all the package versions must be bumped in batch. These commands might look like this:
```
$ pwd
/Users/massi/work/integrations/packages/apache
$ elastic-package version print
0.1.0
$ elastic-package version bump minor
$ elastic-package version print
0.2.0
```

This way, in case of batch updates similar to the linked PR, one might just do:
```
$ pwd
/Users/massi/work/integrations/packages
$ find . -type f -maxdepth 2 -execdir elastic-package version bump bugfix \;
```

**Comment by mtojek** [comment]
@masci I'm wondering if we still need this feature. I suppose that we ended up the era of massive package modifications (breaking changes that affect package format), so this issue seems to be really low priority or even not needed anymore. I would be for closing it, WDYT?

**Comment by mtojek** [comment]
Consulted offline with Massi and decided to close this one.
