### ISSUE TITLE
Replace `$json` with `json` when generating package READMEs

### ISSUE THREAD

**Issue by jen-huang** [elastic/elastic-package#371]
See https://github.com/elastic/kibana/issues/101168 for issue details. There is a fix in Kibana to convert the incorrect `$json` language flag to `json` to avoid having to re-release all older package versions (https://github.com/elastic/kibana/pull/101187), but we should fix it in the generator going forward:

https://github.com/elastic/elastic-package/blob/3ebb7c474f589c98412960c656402dc4e66a010f/internal/docs/sample_event.go#L36

**Comment by ycombinator** [comment]
I'm going with this.

**Comment by ycombinator** [comment]
@jen-huang Should the generator emit `json` instead of `$json` only if the package requires a certain version or higher of Kibana?

**Comment by jen-huang** [comment]
@ycombinator No, it should use `json` across the board.

**Comment by ycombinator** [comment]
Sorry @jen-huang, but I just want to triple check: older versions of Kibana will render `json` and `$json` marked snippets correctly but newer versions of Kibana will only render `json` marked snippets correctly, yes?

**Comment by jen-huang** [comment]
@ycombinator That's right!

**Comment by ycombinator** [comment]
Awesome, thanks for confirming @jen-huang!
