### ISSUE TITLE
Shell completions

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-package#402]
With the Cobra v1.2.0 [release](https://github.com/spf13/cobra/releases/tag/v1.2.0), shell completions are automatically supported. We should upgrade the `cobra` dependency and then add `elastic-package completion` to the docs.

**Comment by ycombinator** [comment]
cc: @mtojek @exekias @ruflin

**Comment by endorama** [comment]
`cobra` version has been bumped in #416 

A PR adding documentation for the `completion` command is available in #429
