### ISSUE TITLE
Improve test coverage calculation

### ISSUE THREAD

**Issue by mtojek** [elastic/elastic-package#442]
This issue gathers various ideas for improving test coverage calculation:

> Maybe in the future we can do it at least at the file level, e.g. saying that pipeline tests add coverage for pipelines, but not for the manifest or other config files, and system tests add coverage for all the files.

([link](https://github.com/elastic/elastic-package/pull/441#discussion_r674668360))

**Comment by jsoriano** [comment]
Several improvements in test coverage have been done, closing this. We can open specific issues for specific improvements.
