### ISSUE TITLE
External ECS field definition of geo_point fails validation

### ISSUE THREAD

**Issue by andrewkroh** [elastic/elastic-package#445]
When using an external ECS definition of a `geo_point` field the validation of a document's fields fails.

```
# data_stream/log/fields/ecs.yml
- name: source.geo.location
  external: ecs
```

```
FAILURE DETAILS:

[0] field "source.geo.location.lat" is undefined
[1] field "source.geo.location.lon" is undefined
```

**Comment by andrewkroh** [comment]
@mtojek Was this one fixed by your https://github.com/elastic/elastic-package/pull/476?

**Comment by mtojek** [comment]
Yes, Andrew. The fix has been also pulled to elastic/integrations.
