### ISSUE TITLE
Discuss: Use mage instead of make

### ISSUE THREAD

**Issue by ruflin** [elastic/elastic-package#49]
Currently the project uses a Makefile. By now most of our other go projects have move to using mage to make it better cross platform compatible. I would encourage as long as the Makefile is still simple to start moving magefiles instead.

**Comment by mtojek** [comment]
Actually it's the other way round. I talked about this with @exekias .

Using the `mage` builder made the debugging process of the Beats building code really difficult. Same for integrations. As long as we don't need any advanced actions, I would suggest to keep the plain old Makefile.

(Personal opinion) I suggest to get rid of magefiles wherever if it's possible as we tend to sneak too much logic there.

**Comment by mtojek** [comment]
It looks like we play well with "make", so let's leave this discussion for now.
