### ISSUE TITLE
Kubernetes service deployer: use correct stack version

### ISSUE THREAD

**Issue by mtojek** [elastic/elastic-package#567]
@ChrsMark opened this [issue](https://github.com/elastic/integrations/pull/2041):

>@mtojek I think that the issue is that elastic-agent Pod is not deployed using the proper version, and even if the stack is 7.16 or 8.0 it will use 7.15.1 because at https://github.com/elastic/elastic-package/blob/2c331472bb62cc53a12c9ba3ec695dba28e1cc61/internal/testrunner/runners/system/servicedeployer/kubernetes.go#L170 it seems to use the DefaultStackVersion which is 7.15.1.

>Changing this on my local elastic-package source code to use 7.16.0-SNAPSHOT and it works. Wondering what is the proper way to handle it though. Shouldn't this runner honor the value of --version flag that is set when bringing up the stack?

The goal of this issue is to detect the stack version and select appropriate version of elastic-agent.

**Comment by ChrsMark** [comment]
Thank you! A solution might be that we use a `--version` flag for running system tests which means that we have the flexibility to run tests a specific version of Agent even if the version of the stack is not same.

**Comment by mtojek** [comment]
It seems possible to read the stack version from the running Kibana with following steps:

1. Fetch content of http://localhost:5601/login
2. Find `kbn-injected-metadata`: 
3. 
```
<kbn-injected-metadata data="{&quot;version&quot;:&quot;7.15.1&quot;,&quot;buildNumber&quot;:44185...
```

3. Extract the version: `7.15.1` in this case.

Let me know what you think, @ChrsMark @jsoriano .

**Comment by jsoriano** [comment]
> Let me know what you think

As discussed offline I agree with this approach by now. Tested and it works with snapshots too:
```
kbn-injected-metadata data="{&quot;version&quot;:&quot;7.15.2-SNAPSHOT&quot;
```

In the future we may try to leverage the profiles to pass information through `shellinit` or similar.

**Comment by ChrsMark** [comment]
No objection from my side if it works for snapshot versions too, like `7.16.0-SNAPSHOT`.

**Comment by mtojek** [comment]
Ok, I'm giving this method a try and will implement it.
