### ISSUE TITLE
Publish zipped packages and matching signatures

### ISSUE THREAD

**Issue by jlind23** [elastic/elastic-package#583]
The goal of this issue is to publish .zip archives and matching signatures to the Package Storage v2.

Related issue:
- [ ] https://github.com/elastic/elastic-package/issues/576

TODO
- [ ] Create a follow-up issue for Kibana to validate signatures.

**Comment by mtojek** [comment]
Together with Robots and Infra teams we discussed possible options. We'll come back with an idea for a publishing pipeline.

**Comment by mtojek** [comment]
The mechanism is already in place. We need to repack and sign existing packages, which is in the scope of https://github.com/elastic/package-storage/issues/2776.
