### ISSUE TITLE
Expand `elastic-package export` to include Elasticsearch objects

### ISSUE THREAD

**Issue by DJRickyB** [elastic/elastic-package#600]
Currently, the `export` command only supports Kibana Dashboards.  Our team would like support for `elastic-package export` to include Elasticsearch assets from the integrations, specifically:

* ILM Policies*
* Composable Templates
* Index Template Settings/Mappings Components
* Ingest Pipelines
* Transforms

*This is not currently in the [package spec](https://github.com/elastic/package-spec#supported-assets), but if in actuality it is or becomes available in a package, we would want to grab it.

Also: a nice-to-have as a result of expanding the types available to `export` would be the specification of a target dir for the output artifacts.

**Comment by tomcallahan** [comment]
@jlind23 any estimate on when you'll get to this? It'd be helpful for our planning

**Comment by jlind23** [comment]
@tomcallahan we'll try to make it land before the end of February. Would it be ok on your hand?

**Comment by mtojek** [comment]
@tomcallahan There is also another option. If you're on a tight schedule, but feel that you can implement this feature earlier, we can help you with reviewing. We used to go that way before a few times and it worked pretty well

**Comment by jlind23** [comment]
The best option here as discussed with both @jsoriano and @mtojek is to have a subcommand in the export command to differentiate performance export from others.

**Comment by jsoriano** [comment]
Working on this, I think we can get all the info from the installed data streams, using the package as input:
* ILM Policies <- from data streams
* Index Templates <- from data streams
* Composable Templates <- from index templates (composed_of field)
* Ingest Pipelines <- from index templates (template.settings.index.default_pipeline)
* Transforms don't seem to be used so far.

**Comment by mtojek** [comment]
> using the package as input

Just to clarify, you're referring to the remote, installed package in Kibana, right?

**Comment by jsoriano** [comment]
> > using the package as input
> 
> Just to clarify, you're referring to the remote, installed package in Kibana, right?

Yes. I use the data streams API to discover them, I will open a PR soon.
