### ISSUE TITLE
Automate Package Promotion to Production

### ISSUE THREAD

**Issue by jamiehynds** [elastic/elastic-package#642]
Releasing new integrations, and updates to existing integrations, is currently a manual process, often leading to integrations being 'stuck' in staging for long periods of time without being released. There is no regular cadence as to when new integrations are promoted from staging to production, making it hard to co-ordinate marketing activities and informing users that new integrations are available. 

Can this process be automated to ensure that integrations are pushed to production on a regular cadence? QA will of course be required, with approval from the SEI/O11Y integration team before pushing to production. Some integrations will require approval from both teams (e.g. System integration which includes intergraions owned by both teams) An email notification to both teams with a list of changes to be pushed would be great - especially as a PM, where I can co-ordinate the various integration launch activities. @andrewkroh may be some additional thoughts as to how we approach this. 

The Security External Integrations team are willing to lead this effort, as we regularly ship new integrations and the lack of automation is a pain point.

 Before we invest in this effort, we'd like to get input from the o11y team - @akshay-saraswat @jlind23 @mtojek @ruflin

**Comment by mtojek** [comment]
> Releasing new integrations, and updates to existing integrations is currently a manual process, often leading to integrations being 'stuck' in staging for long periods of time without being released. There is no regular cadence as to when new integrations are promoted from staging to production, making it hard to coordinate marketing activities and inform users that new integrations are available.

This is rather a problem of ownership in Observability that developers forget to publish their changes (owning from implementing it to releasing). As you mentioned the marketing activities, in some cases the package needs to wait for publishing due to other constraints which might be hard to automatically coordinate (auto-push if tests are passing).

> Before we invest in this effort, we'd like to get input from the o11y team - @akshay-saraswat @jlind23 @mtojek @ruflin

I'm not sure if you want to invest in this as we are working on getting rid of the Package Storage in the Git repository. We're in the middle of changing the storage layer to a new form (based on object storage), which doesn't assume any stages (snapshot, staging, production). It will depend strictly on semver tags and will be flat storage).

It would be great, Jamie, if you can describe your idea mission control panel, use-case, workflow, etc. so that we can meet your expectations with the redesign.

**Comment by jlind23** [comment]
Hi @jamiehynds 

What will then be the rules of that automation? 
Something like as soon as something is tagged as GA it should be pushed all the way through to production? Am i right?
What worries me is that automations are dumb and we may end up with packages in production due a mistake and thus being unable to remove them gracefully.
As @mtojek said, we are currently working on redesigning those stages and having something more easy to consume, we won't rely on stage but rather on integrations status, so as soon as you push an integration is will be publicly available whatever the status it has.

Please @akshay-saraswat jump in

**Comment by jamiehynds** [comment]
Thanks for the feedback @mtojek and @jlind23 

My team and I weren't aware of the planned changes around package storage and the redesign of the various stages. Is there an issue associated that we could read up on?

Focusing more on integration status seems to make sense. The biggest problem we face today is integrations being pushed to staging but end up sitting there for longer than planned as engineers work on other tasks. Oftentimes, the integration has come in via a community contribution so the engineer that reviewed the PR hasn't necessarily worked on the integration end-to-end. Maybe an email notification after X number of days with a list of integrations in staging (along with responsible engineer/team) is an option. But if we're moving away from the current stages, probably not worth investing in for now. 

I'm ok to close this one out for now - and my team and I can provide input on the redesign if it's helpful to the ecosystems team.

**Comment by mtojek** [comment]
Hey Jamie,

I will send up a direct email with the most important links around that topic.

BTW I thought I saw Andrew Kroh commenting somewhere in the docs, so we assumed that you're familiar with the entire initiative.

**Comment by jamiehynds** [comment]
Thanks @mtojek! Will close this out one for now.
