### ISSUE TITLE
stack command: start selected services only

### ISSUE THREAD

**Issue by mtojek** [elastic/elastic-package#72]
Pipeline tests (see: https://github.com/elastic/elastic-package/issues/15) require only the Elasticsearch instance, so it's not necessary to boot up the entire stack.

Maybe the `stack up` subcommand should expose additional parameters like service names? e.g. `elasticsearch`, `kibana`, `package-registry`

**Comment by mtojek** [comment]
@ycombinator @ruflin do you have any preferences?

**Comment by ruflin** [comment]
+1 on not booting Kibana for these tests. I think it might be confusing the stack provides a flag to not start the stack.

There is also the part that for just the ingest pipeline testing you don't need security and probably other params. I would put it separate for now.

**Comment by mtojek** [comment]
> +1 on not booting Kibana for these tests. I think it might be confusing the stack provides a flag to not start the stack.

It depends on how do you look at it. We can say the `stack up` subcommand allows for selection of stack components.

**Comment by mtojek** [comment]
I will need this one before enabling it in the Integrations repository. Otherwise, people might feel confused why do they need to spin up Kibana for `mage check` if they are not gonna use it.
