### ISSUE TITLE
[lint] Validation error when using external ECS @timestamp definition

### ISSUE THREAD

**Issue by andrewkroh** [elastic/elastic-package#749]
Defining `@timestamp` with an `external: ecs` definition fails linting. For example:

```
# fields/ecs.yml
- external: ecs
  name: '@timestamp'
```

It seems that all packages currently have an `@timestamp` defined in their `base-fields.yml` and do not use the ECS definition. When you remove that definition and try to rely on the ECS definition `lint` fails.

```
Lint the package
Error: linting package failed: found 2 validation errors:
   1. expected type "date" for required field "@timestamp", found "" in "/Users/akroh/code/elastic/integrations/packages/crowdstrike/data_stream/falcon/fields/ecs.yml"
   2. expected type "date" for required field "@timestamp", found "" in "/Users/akroh/code/elastic/integrations/packages/crowdstrike/data_stream/fdr/fields/ecs.yml"
```

**Comment by jsoriano** [comment]
We will have to relax this check in the package spec for fields with `external: ecs`: https://github.com/elastic/package-spec/blob/02e9a7fd88fec29302517e89d49879da2f6a3050/code/go/internal/validator/semantic/validate_required_fields.go#L51
