### ISSUE TITLE
Provide a way to label resources created by Terraform Deployer

### ISSUE THREAD

**Issue by endorama** [elastic/elastic-package#754]
Terraform deployer allow to setup test infrastructure for `system` tests.

Currently it injects an environment variable, `TEST_RUN_ID` that can be used to provide unique name to resources, but there is no way to link this ID to the pull request the test run has been started from.

Linking resources to a PR is helpful in 2 main cases:
- debugging test infrastructure 
- remove eventual leftovers from CI runs, that may happen either due to errors or missed teardown (is possible teardown is not completed in some edge cases)
 
The proposal is to add 2 environment variables:
- `GITHUB_REPO`: es `elastic/integrations`, contains information on the repository that created the resources
- `GITHUB_PR`: es `1234`, contains the PR number that created the resources

Those variable could then be leveraged by developer writing test leveraging the Terraform deployer to tag created resources.

**Comment by mtojek** [comment]
There might be a quick win possible if we add support for [REPO_BUILD_TAG](https://github.com/elastic/elastic-package/blob/main/.ci/package-storage-publish.groovy#L9) in [env.yml](https://github.com/elastic/elastic-package/blob/main/test/packages/parallel/gcp/data_stream/compute/_dev/deploy/tf/env.yml#L8), and accordingly in the .tf files as labels.
