### ISSUE TITLE
Reviews are requested in package-storage —can we change to an @-mention instead?

### ISSUE THREAD

**Issue by jasonrhodes** [elastic/elastic-package#780]
[This code](https://github.com/elastic/elastic-package/blob/58aa8b362bda8f132b8cc43d757954937cd9d2c6/internal/publish/pull_requests.go#L109) appears to look at the package's manifest.yml file and find [the owner of the package](https://github.com/elastic/integrations/blob/main/packages/kibana/manifest.yml#L51-L52) and use that information to assign that owner as a reviewer on [the PR generated in the package-storage repo](https://github.com/elastic/package-storage/pull/3905). However, as far as I can tell, no review is actually required for this repo (the review for the associated change would have happened in the elastic/integrations repo). 

It would be helpful for the teams that own these packages to not have to remember that this repo doesn't require the review that the bot assigned, and instead have the bot leave a comment like:

"@-team, please be aware that this package is now being updated" - even better if it could reference the integrations PR that kicked this update off!

**Comment by jsoriano** [comment]
Package storage is not used anymore, and changes have been introduced in the integrations repository to require reviews of code owners. We also notify now in PRs when a package is published including this PR. So probably the situation regarding the issues described here is better now. Closing this, please create new issues if you still have problems with the current ecosystem.
