### ISSUE TITLE
feature-request: option to pin local registry image

### ISSUE THREAD

**Issue by efd6** [elastic/elastic-package#804]
When bringing the stack up, currently elastic-package gets the latest snapshot of the registry. This is almost always the right thing to do. However, on occasions when the most current registry is not required, but the stack needs to be restarted the need to pull ~900MB impacts on developer iteration time, and in some cases available bandwidth.

It would be nice if it were possible for the user to pin the image that docker compose uses to the image that is available on local storage rather than getting the current snapshot.

**Comment by efd6** [comment]
An alternative approach which would satisfy the development use case would be to enable pulling a naked registry that only uses the local packages by tagging the image prior to the addition of the package data during the image build. This would reduce the pull size by about 100 fold and would be enable rapid iteration while developing/debugging packages.

**Comment by jsoriano** [comment]
@efd6 yes, [we are considering](https://github.com/elastic/package-spec/issues/346#issuecomment-1184634597) using a bare image for package development.

https://github.com/elastic/kibana/issues/70582 would also allow to do package development without even needing a registry.

**Comment by efd6** [comment]
Is there a timeframe for this? It is a significant pain point for development.

**Comment by jsoriano** [comment]
@efd6 is this an issue when running `elastic-package stack up` only or when `elastic-package stack update` is involved?

Btw, as part of the storage v2 efforts we have started to build a "lite" image, that could help with this.

https://github.com/elastic/package-registry/issues/770 can also help as then the local registry would be minimal.

**Comment by efd6** [comment]
The happens when I do a stack up, even just to pick up changes for system testing with `elastic-package stack up -d -v -s package-registry`. With bad timing, what should take a minute or so, takes as long as needed to pull, now, 1GB.

**Comment by jsoriano** [comment]
Umm, there may be some issue there, I think `elastic-package stack up` shouldn't pull images that are locally available.

**Comment by jsoriano** [comment]
Yes, I currently have an outdated version of `docker.elastic.co/package-registry/distribution:snapshot`, and the new one is not downloaded by `elastic-package stack up`, but it is if I run `elastic-package stack update`.

@efd6 what versions of `elastic-package` and `docker-compose` are you using?

**Comment by efd6** [comment]
Docker Compose version v2.6.1
elastic-package 353ea8779a5e734908b58cfabb4d3e6881602aca

**Comment by mtojek** [comment]
We implemented the [proxy mode](https://github.com/elastic/package-registry/issues/770), so I guess that this issue isn't relevant anymore.

**Comment by efd6** [comment]
Is there documentation for how that would be used to solve this.

**Comment by mtojek** [comment]
No, it's enabled by default. It's transparent for developers.
