### ISSUE TITLE
[field validation] Check event.type values are aligned with event.category

### ISSUE THREAD

**Issue by andrewkroh** [elastic/elastic-package#837]
The `event.type` values are constrained based on the `event.category` values. Each category value has an expected list of `event.type` values that can be used. ECS lists these values `expected_event_types` in `ecs_flat.yml` [^1].

As a package developer I would like elastic-package to validate the event.category and event.type combinations used events to ensure they are allowed by ECS.

Related

- https://github.com/elastic/elastic-package/issues/615
- https://github.com/elastic/integrations/pull/3424#discussion_r881667201

[^1]: https://github.com/elastic/ecs/blob/b2df3bc395e125b9380a25e009eddef1b1890476/generated/ecs/ecs_flat.yml#L2645-L2648

**Comment by jsoriano** [comment]
Putting this also on hold till we have something like https://github.com/elastic/package-spec/issues/313.
