### ISSUE TITLE
[System test runner] Use volume mounts for logs

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-package#85]
Follow up to https://github.com/elastic/elastic-package/pull/64, based on suggestion in https://github.com/elastic/elastic-package/pull/64#discussion_r481066466:

> I wonder if we can simplify this - we still have a volume with log files mounted, so maybe don't depend specifically on stdout and stderr, but just share a volume between agent and the service. I'm fine with discussing this in a different issue.

**Comment by mtojek** [comment]
@ycombinator it would beneficial for this task to finalize the PR https://github.com/elastic/integrations/pull/263 first.

**Comment by mtojek** [comment]
I did an investigation and tried different options.

Problem: share all logs between Agent and the service under test (SUT).

Requirements:
1. Long running Elastic stack.
2. No parallel tests (at least at the moment).
3. Logs cleanup after SUT shutdown.

Options:

1. Create external volume (`docker volumes create`?).

Before starting the Elastic stack we can create the volume and mount it in Agent and SUT containers during startup.
Cleanup might be hard to perform as we need to sneak into the volume and wipe the content.

2. Boot up SUT as part of the project (`docker-compose up`).

SUT can share the volume created by the previous boot of the Elastic stack.
The problem with cleanup remains - we need to sneak into.

3. Use `tmp/service_logs ` system directory.

The temporary directory is bound to the normal filesystem path. The directory can be shared between Elastic Agent, SUT and test runner (!).
The test runner  can clean the service logs after test execution.

**Comment by ycombinator** [comment]
I'm also in favor of option 3. It is in the same general mold as what we are currently doing, except it uses volumes for sharing the services log files between containers instead of stream redirection.
