### ISSUE TITLE
[System test runner] Cleanup old test assets before each run?

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-package#88]
Follow up to https://github.com/elastic/elastic-package/pull/64, based on discussion in https://github.com/elastic/elastic-package/pull/64#discussion_r481059641:

> ... we have the same identifiers for each test run. Then we clean up resources before (and after) the test run starts, in case any resources were left from transient failures from a previous run... we need to account for orphan resources due to transient failures from previous runs.

> As long as we don't have intention to run tests in parallel, this can work pretty well. Agree for introducing such mechanism. I'm also fine with postponing it to the next iteration.

> Actually, what I suggested above is not trivial to implement for policies as their IDs are generated by Kibana. We could retrieve all policies and delete ones that match a certain naming convention, but let's worry about that in a follow up PR.

**Comment by mtojek** [comment]
We're cleaning used resources now. Resolving.
