### ISSUE TITLE
[docs] Add new docs template language to `elastic-package create package`

### ISSUE THREAD

**Issue by colleenmcginnis** [elastic/elastic-package#880]
In elastic/integrations#3433, we're working on the first iteration of more detailed documentation guidelines for integrations (including template language). In that PR @jsoriano suggested:

>`elastic-package create package` can be used to create an initial scaffolding for new packages, as a follow up we could apply these recommendations in the templates there.

We should do this after elastic/integrations#3433 is merged.

cc @jamiehynds @elastic/obs-docs

**Comment by colleenmcginnis** [comment]
@jsoriano is this something I could help with or is it something your team needs to do?

**Comment by jsoriano** [comment]
@colleenmcginnis it would be great if you can open a PR with the proposed changes, we would be happy to review :slightly_smiling_face:

The code to generate packages is around here: https://github.com/elastic/elastic-package/tree/3e52239e64ffa9c6f912592204d119cd88451a2a/internal/packages/archetype

I see that this is mostly go code, we could maybe migrate it first to use templates if this makes it easier to make changes there.

Let us know what approach do you prefer.

**Comment by colleenmcginnis** [comment]
Thanks @jsoriano! I'll give it a try next week.
