### ISSUE TITLE
Enable stack components logging

### ISSUE THREAD

**Issue by crespocarlos** [elastic/elastic-package#907]
Currently elastic-agent container bind-mount this folder `/tmp/service_logs/`, with that we could enable Kibana and Elasticserch to generate logs into this folder.

Neither Elasticsearch nor Kibana are enabled to generate logs, and this causes manual changes to the config files in order to have them created and watched by the agent. 

So we would have to include the logging configuration to `kibana.config*.yml` file and `elasticserach.config*.yml` files as well as bind mount the same `/tmp/service_logs/` folder that the elastic-agent watches for. It would be nice to have this via configuration or even in the default setup of elastic-package.

**Comment by jsoriano** [comment]
> So we would have to include the logging configuration to `kibana.config*.yml` file and `elasticserach.config*.yml` files as well as bind mount the same `/tmp/service_logs/` folder that the elastic-agent watches for. It would be nice to have this via configuration or even in the default setup of elastic-package.

Do you mean in the ES and kibana instances started by `elastic-package stack`?

We would prefer to don't consider stack components as special cases. Their integrations should be tested as any other service, using scenarios defined in `_dev/deploy`.

They shouldn't use the components managed by `elastic-package stack`. Apart of making them different to the integrations of other services, this creates an undesired dependency between tests and `elastic-package stack`. At some point we may decide to completely change the architecture of `elastic-package stack`, or deploy the stack in cloud, tests should continue working using environment variables as the ones in `elastic-package stack shellinit`.

**Comment by crespocarlos** [comment]
> Do you mean in the ES and kibana instances started by elastic-package stack?

Yes. The point here is not to change how the packages are installed or create special scenario for them.

The idea is to enable logging for ES and Kibana from `elastic-package stack` in a way that the agent from `elastic-package` can read the files, not make packages dependable on them but to enable a real-world scenario, where agents can read log files that could be ingested by any package. 

What I'm proposing here is just to connect some dots. Enable both Kibana and ES to generate logs in a folder that `elastic-package` agent can read them.

Let me know if this make sense to you

**Comment by jsoriano** [comment]
> enable a real-world scenario, where agents can read log files that could be ingested by any package.

In general, packages must define their own testing scenarios for system tests in `_dev/deploy`. This is what we are also doing in the Package Registry integration in https://github.com/elastic/integrations/pull/3671, even when `elastic-package stack` also starts a registry.
If we use the services started by `elastic-package stack` to test the `elasticsearch`, `kibana` or `package-registry` integrations we are considering them special cases, creating couplings in ways that limit both what we can do in `elastic-package stack`, and what can be done in testing scenarios for these integrations.

Having a separate monitoring cluster is also a real-world scenario that we actually recommend for production environments. If the package defines its own scenario in `_dev/deploy`, it would be monitored by a separate cluster, the one started by `elastic-package stack`.

Having the scenario in `_dev/deploy` will give you more flexibility on the options you can use, it will also allow you to use variants to test with multiple versions or configurations. In general it will give you access to any feature implemented in `elastic-package` for packages system testing.

The stack started by `elastic-package stack` doesn't guarantee more interfaces for testing than what are provided by `elastic-package stack shellinit`, accessing this cluster by other means somehow violates the boundaries of this interface, and you may face unexpected failures if we make changes in how `elastic-package stack` configures the services.

**Comment by crespocarlos** [comment]
I see. I hadn't explored this option of creating my own scenario in `_dev/deploy` before.

I've managed to create my own docker-compose file containing a Kibana container, using another port, that connects to elastic, fleet and agent from `elastic-package stack`. Does this violate the aforementioned boundaries?

**Comment by jsoriano** [comment]
> I've managed to create my own docker-compose file containing a Kibana container, using another port, that connects to elastic, fleet and agent from `elastic-package stack`. Does this violate the aforementioned boundaries?

This is an interesting mixed approach. If you do this to test the kibana integration, and you can use the `ELASTIC_PACKAGE_ELASTICSEARCH_*` environment variables to connect with ES I guess that this is fine.

**Comment by crespocarlos** [comment]
Nice! I guess we can close this ticket then. Thanks!

Maybe the doc could be improved to make it more evident that we can use `elastic-stack service` for testing purposes with some examples of what can be done with it? Currently the doc mentions the `_dev/deploy` folder, but it's very high level.

**Comment by jsoriano** [comment]
Yep good point, we should document this, I have opened an issue for that https://github.com/elastic/elastic-package/issues/915. Thanks!
