### ISSUE TITLE
[System test runner] Support use of deployment variants

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-package#94]
Enhance `elastic-package test system` to support variations of deployments for the service under test. For example, we may want to test against a specific version of the service.

The variations will be defined in the `_dev/deploy/variants.yml` file, for example:

```yml
variants:
  v1:
    SERVICE_VERSION: 1.19.1
  latest:
    SERVICE_VERSION: 2.3.0
default: latest
```

In this case the `elastic-package test system` command might take an optional flag that allows the selection of a specific variant, e.g. `elastic-package test system --deploy-variant=latest` (no strong opinions about the specific flag name). When the flag is not specified, the variant defined in the `default` property should be selected. The flag may take a special value, e.g. `__random__`, that will randomly select a variant for the test (again, no strong opinions on the value name).

When the variant is selected, all the variables defined under it must be made available to the service deployer so it may deploy the package's service(s) after interpolating these variables wherever appropriate, e.g. in the service's `docker-compose.yml` file.

Related: https://github.com/elastic/integrations/issues/781

**Comment by mtojek** [comment]
Let me research the scope of changes.

**Comment by mtojek** [comment]
It seems to be possible to implement it:

1. Implement logic to read available `variants` with environment variables from `variants.yml`.
2. System test runner: iterate over variants and test config files.
3. Pass variant info to `runTest`: https://github.com/elastic/elastic-package/blob/master/internal/testrunner/runners/system/runner.go#L164
4. Extend `servicedeployer.Factory()` to consider variant info: https://github.com/elastic/elastic-package/blob/d7dd1a3ac595583af20e91f3076edb095ea97bd5/internal/testrunner/runners/system/runner.go#L249
5. `elastic-package service up`: select/list variants
