### ISSUE TITLE
"stack up" ignores all but first service

### ISSUE THREAD

**Issue by andrewctate** [elastic/elastic-package#941]
### The problem
When I run
```elastic-package stack up -v -d --services package-registry kibana```
 only the package registry is built and started.

When I run
```elastic-package stack up -v -d --services kibana package-registry```
both services are started, but only because Kibana depends on the package-registry. I.e. leaving off the `package-registry` service results in the same outcome.

### I would expect 
```elastic-package stack up -v -d --services kibana package-registry``` 
to be equivalent to 
```elastic-package stack up -v -d --services package-registry kibana``` 

and I would expect both commands to both start Kibana and rebuild the package registry container with any newly built packages.

**Comment by jsoriano** [comment]
Hey @andrewctate,

The `--services` flag expects a comma-separated list of services, so it would expect: `elastic-package stack up -v -d --services kibana,package-registry`.

This is described in the help texts of `elastic-package stack up --help`:
```
  -s, --services strings   component services (comma-separated values: "elasticsearch,fleet-server,kibana,package-registry,elastic-agent")
```

What is true is that the command should fail if there are additional unparsed arguments, I have created an issue for this: https://github.com/elastic/elastic-package/issues/942

Thanks for reporting!

**Comment by andrewctate** [comment]
Thanks, @jsoriano . In a perfect world I would have read the help text _before_ using the command, but I think https://github.com/elastic/elastic-package/issues/942 would have sent me looking after using it incorrectly the first time.
