### ISSUE TITLE
CLI command to attach a package policy to the Agent

### ISSUE THREAD

**Issue by klacabane** [elastic/elastic-package#952]
### Summary

The `elastic-package install` command currently installs a package assets. It would be useful to also have a command to attach an integration policy of the installed package to the elastic-agent started by the stack, after prompting for the inputs configuration. This will avoid UI configuration and enable automation of the package installation.

It could be a flag provided to `install` or its own dedicated command

**Comment by klacabane** [comment]
The [system tests](https://github.com/elastic/elastic-package/blob/main/docs/howto/system_testing.md#test-case-definition) already do that by enrolling a new agent with policies defined in test configs under `_dev/test/system/`. Would it make sense to reuse that logic to have an agent continuously running with these configs ?

**Comment by jsoriano** [comment]
As discussed over slack, this feature makes sense, it could be something like `elastic-package install --attach <agent id>`. https://github.com/elastic/kibana/issues/70582 would help to use this feature with any package on any cluster.

**Comment by klacabane** [comment]
After a first look at the workflow and code, the following two steps are required:

* Create and configure the integration. We need a way to build the integration inputs and the ability to provide variables like hosts, credentials... In system tests we define a static yml configuration ([example](https://github.com/elastic/integrations/blob/main/packages/elasticsearch/data_stream/cluster_stats/_dev/test/system/test-default-config.yml)) that allows configuration for a single data stream.
This should not be much different than what is already done, we'll only have to extend the capability to cover multiple streams: similar to the system tests we can build a policy by parsing the package and data stream's manifest, but instead of reading a single stream we'll have to parse every ds defined in `data_streams` directory. We'll then use user-defined configuration file (under `<package>/_dev/policy` ?) that will provide both package and ds variables that need to be substituted. The configuration file's format would like like this:
```yaml
inputs:
  - type: elasticsearch/metrics
    vars:
      hosts:
        - "http://{{Hostname}}:5066"
    streams:
      - dataset: elasticsearch.stack_monitoring.cluster_stats
```

* Attach the integration to an agent policy
Ability to provide an agent id `--attach <agent-id>` or fallback to the first available agent if none provided. [This code already exists](https://github.com/elastic/elastic-package/blob/main/internal/testrunner/runners/system/runner.go#L401-L405) in the system test runner's logic and we should be able to reuse it

**Comment by klacabane** [comment]
Logging observations made while digging further:
- variables can be defined at package, input and data stream levels
- the configuration should be the starting point for the policy, ie we should only enable the inputs/streams set in the configuration instead of enabling every streams by default. This is to accommodate larger integration like [the aws one](https://github.com/elastic/integrations/blob/main/packages/aws/manifest.yml) that defines one policy template per service. Considering a use case where one would use the `--attach` functionality in aws package, I don't think enabling every single service would happen but we would instead prefer installing only the cloudwatch or ec2 integration only
- the last point suggests that we may want multiple configurations files and a way to pass them to the attach command. For example `--attach ec2-policy.yml`
